# %%writefile name.py -> To create module

In [285]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
data = pd.read_csv("final_data.csv",encoding = "cp1252")
data

,Unnamed: 0,company_name,old,total_employees,cities,type,industry,rating
0,0,Zydus Lifesciences,72 years old,10k-50k Employees,Ahmedabad,Public,Pharma,4-5
1,1,Intas Pharmaceuticals,47 years old,10k-50k Employees,Ahmedabad,Fortune India 500,Pharma,4-5
2,2,Vodafone Idea,6 years old,5k-10k Employees,Ahmedabad,Public,Telecom,4-5
3,3,TTEC India,40 years old,1k-5k Employees,Ahmedabad,Public,Bpo,3-4
4,4,Cadila Pharmaceuticals,73 years old,5k-10k Employees,Ahmedabad,Public,Pharma,3-4
...,...,...,...,...,...,...,...,...
25373,25373,GlaxoSmithKline Consumer Healthcare,24 years old,1k-5k Employees,Pune,Public,Pharma,4-5
25374,25374,Radio City,23 years old,201-500 Employees (Global),Pune,Public,Broadcasting,3-4
25375,25375,N.C.L. Industries,44 years old,501-1k Employees,Pune,Public,Building Material,3-4
25376,25376,Grab (India),12 years old,5k-10k Employees,Pune,Startup,Internet,4-5
25377,25377,Snapbizz,11 years old,51-200 Employees,Pune,Startup,Software Product,3-4

In [4]:
data = data.drop(["Unnamed: 0"],axis = 1)
data

,company_name,old,total_employees,cities,type,industry,rating
0,Zydus Lifesciences,72 years old,10k-50k Employees,Ahmedabad,Public,Pharma,4-5
1,Intas Pharmaceuticals,47 years old,10k-50k Employees,Ahmedabad,Fortune India 500,Pharma,4-5
2,Vodafone Idea,6 years old,5k-10k Employees,Ahmedabad,Public,Telecom,4-5
3,TTEC India,40 years old,1k-5k Employees,Ahmedabad,Public,Bpo,3-4
4,Cadila Pharmaceuticals,73 years old,5k-10k Employees,Ahmedabad,Public,Pharma,3-4
...,...,...,...,...,...,...,...
25373,GlaxoSmithKline Consumer Healthcare,24 years old,1k-5k Employees,Pune,Public,Pharma,4-5
25374,Radio City,23 years old,201-500 Employees (Global),Pune,Public,Broadcasting,3-4
25375,N.C.L. Industries,44 years old,501-1k Employees,Pune,Public,Building Material,3-4
25376,Grab (India),12 years old,5k-10k Employees,Pune,Startup,Internet,4-5
25377,Snapbizz,11 years old,51-200 Employees,Pune,Startup,Software Product,3-4

In [5]:
def all_locations():
    return data[~data["cities"].isna()]["cities"].apply(lambda x :x.split(" +")[0].strip().title()).unique()

In [6]:
all_locations()

array(['Ahmedabad', 'Indore', 'Mundra', 'Noida', 'Mumbai',
       'Gurgaon/Gurugram', 'Durham', 'Bangalore / Bengaluru',
       'Greater Noida', 'Gurgaon', 'Delhi', 'Goa', 'Dahej', 'Kolkata',
       'Gurgaon / Gurugram', 'Vadodara', 'Varanasi', 'Jaipur',
       'Hyderabad / Secunderabad', 'Pune', 'New Delhi',
       'Silvassa / Dadra & Nagar Haveli', 'Bhubaneswar', 'Bangalore',
       'Dublin', 'Teaneck. New Jersey.', 'Bangalore/Bengaluru', 'Paris',
       'Bengaluru/Bangalore', 'New York', 'Fremont', 'Navi Mumbai',
       'Seattle', 'Armonk', 'Chennai', 'Hisar', 'Satna', 'Hosur',
       'Kalyani', 'Maunath Bhanjan', 'Chamba', 'Nagpur', 'Zurich',
       'Chiyoda-Ku', 'Sunnyvale', 'Hyderabad/Secunderabad', 'Ypsilanti',
       'San Francisco', 'Wedel', 'Boulogne Billancourt Cedex',
       'Noblesville', 'Gurugram', 'Kochi', 'Ranipet', 'Schaffhausen',
       'Patancheru', 'Ambernath', 'Abohar', 'Madurai', 'Aurangabad',
       'Agra', 'Jacksonville', 'Hyderabad', 'Coimbatore', 'Sonipat',
       'Ballari', 'Delhi/Ncr', 'Khatima', 'San Mateo', 'Shanghai',
       'Patna', 'Thane', 'Anjar', 'Slough', 'Cupertino', 'Minnetonka',
       'Menlo Park', 'Dehradun', 'Faridabad', 'Michigan',
       'Haidian District', 'Cincinnati', 'Kharagpur', 'Gajraula', 'Surat',
       'Alwar', 'Jodhpur', 'Chandigarh', 'Barbil', 'Karnal', 'Norwalk',
       'Nagar', 'Udaipur', 'Mohali', 'Rishikesh', 'Kalyan / Dombivli',
       'Ankleshwar', 'Boisar', 'Tirupati', 'Khopoli', 'Canonsburg',
       'Warangal', 'Wayzata', 'Nashik', 'Daman & Diu', 'Rajkot',
       'Pithampur', 'Bina', 'Lucknow', 'Dubai', 'Rayagada', 'Bhuj',
       'Stockholm', 'Seoul', 'New York City', 'Bharuch', 'Singapore',
       'Osaka', 'Morris Plains', 'Jalandhar', 'Gandhinagar', 'Shenzhen',
       'Satara District'], dtype=object)

In [7]:
def all_types():
    return data[~data["type"].isna()]["type"].apply(lambda x :x.strip().title()).unique()

In [8]:
all_types()

array(['Public', 'Fortune India 500', 'Forbes Global 2000',
       'Indian Unicorn', 'Conglomerate', 'Startup', 'Government'],
      dtype=object)

In [9]:
def all_industries():
    return data[~data["industry"].isna()]["industry"].apply(lambda x :x.strip()).unique()

In [10]:
all_industries()

array(['Pharma', 'Telecom', 'Bpo', 'It Services & Consulting',
       'Analytics & Kpo', 'Fashion & Textile', 'Banking', 'Power',
       'Auto Components', 'Engineering & Construction', 'Healthcare',
       'Automobile', 'Iron & Steel', 'Fmcg', 'Oil & Gas', 'Edtech',
       'Nbfc', 'Financial Services', 'Hardware & Networking',
       'Clinical Research', 'Broadcasting', 'Ports & Shipping',
       'Internet', 'Retail', 'Building Material', 'Industrial Machinery',
       'Insurance', 'Facility Management Services', 'Other', 'Chemicals',
       'Consumer Electronics & Appliances', 'Fintech', 'Logistics',
       'Hospitality', 'Defence & Aerospace', 'Real Estate',
       'Printing & Publishing', 'Agro Chemicals',
       'Electronics Manufacturing', 'Food Processing',
       'Electrical Equipment', 'Management Consulting', 'Aviation',
       'Software Product', 'Media & Entertainment',
       'Chemicals / Agri Inputs', 'Petrochemicals', 'Biotechnology',
       'Recruitment', 'Furniture & Furnishing', 'Beverage',
       'Metals & Mining', 'Packaging', 'Architecture & Interior Design',
       'Beauty & Personal Care', 'Medical Equipment',
       'Industrial Automation', 'Law Enforcement & Security',
       'Education & Training', 'Public', 'Urban Transport',
       'Travel & Tourism', 'Agriculture',
       'Investment Banking / Venture Capital / Private Equity', 'State',
       'Pulp & Paper', 'Jewellery', 'Waste Management',
       'Accounting & Auditing', 'Non-Profit', 'Central', 'Semiconductors',
       'Startup', 'Fitness & Wellness', 'Marketing & Advertising',
       'Computer Software', 'Legal', 'Content Development',
       'Import & Export', 'Design', 'Emerging Technologies',
       'Sports & Recreation', 'Animation & Vfx', 'Gaming', 'Leather'],
      dtype=object)

In [11]:
def search(location = False,rating = False, type_ = False,industry= False ):
        if  location:
            location= data['cities'] == location
        else:
            location = True
        if rating :
            rating = data['rating'] == rating
        else:
            rating = True
        if  type_ :
            type_ = data['type'] == type_
        else:
            type_= True
        if industry :
            industry = data['industry'] == industry
        else:
            industry = True
        return data[location &rating&type_&industry]

In [12]:
search("Mumbai",industry = "Nbfc", type_ = "Public")

,company_name,old,total_employees,cities,type,industry,rating
400,Mahindra Finance,33 years old,10k-50k Employees,Mumbai,Public,Nbfc,4-5
9176,IIFL Finance,29 years old,10k-50k Employees,Mumbai,Public,Nbfc,3-4
9255,REPCO HOME FINANCE,24 years old,501-1k Employees,Mumbai,Public,Nbfc,3-4
9547,Poonawalla Fincorp,36 years old,1k-5k Employees,Mumbai,Public,Nbfc,3-4
19477,LIC Housing Finance,35 years old,1k-5k Employees,Mumbai,Public,Nbfc,3-4
20744,Indostar Capital Finance,13 years old,1k-5k Employees,Mumbai,Public,Nbfc,4-5
21246,IIFL Finance,29 years old,10k-50k Employees,Mumbai,Public,Nbfc,3-4
21276,L&T Finance,30 years old,10k-50k Employees,Mumbai,Public,Nbfc,3-4
21338,Mahindra Finance,33 years old,10k-50k Employees,Mumbai,Public,Nbfc,4-5
21344,Indiabulls Home Loans,19 years old,5k-10k Employees,Mumbai,Public,Nbfc,3-4
21435,Shriram Finance,45 years old,50k-1 Lakh Employees,Mumbai,Public,Nbfc,4-5
21561,Capri Global Capital,27 years old,1k-5k Employees,Mumbai,Public,Nbfc,3-4
21579,Manappuram Finance,75 years old,10k-50k Employees,Mumbai,Public,Nbfc,3-4
21599,Mahindra Rural Housing Finance,17 years old,10k-50k Employees,Mumbai,Public,Nbfc,4-5
21604,BOB Financial Solutions,30 years old,501-1k Employees,Mumbai,Public,Nbfc,4-5
21618,Muthoot Finance,85 years old,10k-50k Employees,Mumbai,Public,Nbfc,3-4
21643,Kogta Financial India Limited,28 years old,1k-5k Employees,Mumbai,Public,Nbfc,4-5
21651,Ugro Capital,31 years old,1k-5k Employees,Mumbai,Public,Nbfc,3-4
21707,Kotak Mahindra Prime,28 years old,5k-10k Employees,Mumbai,Public,Nbfc,3-4
21766,Indostar Capital Finance,13 years old,1k-5k Employees,Mumbai,Public,Nbfc,4-5
21838,Reliance Home Finance,16 years old,501-1k Employees,Mumbai,Public,Nbfc,4-5
21858,Poonawalla Fincorp,36 years old,1k-5k Employees,Mumbai,Public,Nbfc,3-4
21859,LIC Housing Finance,35 years old,1k-5k Employees,Mumbai,Public,Nbfc,3-4
22039,Inditrade Capital,30 years old,201-500 Employees,Mumbai,Public,Nbfc,4-5
22044,Manba Finance,28 years old,501-1k Employees,Mumbai,Public,Nbfc,3-4
22114,Bell Finvest,30 years old,51-200 Employees,Mumbai,Public,Nbfc,2-3
22530,LendingKart,10 years old,1k-5k Employees,Mumbai,Public,Nbfc,3-4
22556,LendingKart,10 years old,1k-5k Employees,Mumbai,Public,Nbfc,3-4
22690,Can Fin Homes,37 years old,501-1k Employees,Mumbai,Public,Nbfc,3-4
22799,Satin Creditcare Network,34 years old,5k-10k Employees,Mumbai,Public,Nbfc,4-5
22801,REPCO HOME FINANCE,24 years old,501-1k Employees,Mumbai,Public,Nbfc,3-4
22813,Satin Creditcare Network,34 years old,5k-10k Employees,Mumbai,Public,Nbfc,4-5
22816,REPCO HOME FINANCE,24 years old,501-1k Employees,Mumbai,Public,Nbfc,3-4
22903,Electronica Finance,34 years old,1k-5k Employees,Mumbai,Public,Nbfc,4-5
22926,Electronica Finance,34 years old,1k-5k Employees,Mumbai,Public,Nbfc,4-5
23027,Paisalo Digital,32 years old,51-200 Employees,Mumbai,Public,Nbfc,3-4
23550,Ugro Capital,31 years old,1k-5k Employees,Mumbai,Public,Nbfc,3-4

In [334]:
%%writefile methods.py

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

data = pd.read_csv("final_data.csv",encoding = "cp1252")
data = data.drop(["Unnamed: 0"],axis = 1)

def all_locations():
    return data[~data["cities"].isna()]["cities"].unique()
def all_types():
    return data[~data["type"].isna()]["type"].unique()
def all_industries():
    return data[~data["industry"].isna()]["industry"].unique()

def search(location="all",rating ="all", type_ ="all",industry= "all"):
    res = data.copy(deep = True)
    if  location != "all":
            res= res[res['cities'] == location]
    if rating != "all":
            res = res[res['rating'] == rating]
    if  type_ != "all":
            res = res[res['type'] == type_]
    if industry != "all":
            res = res[res['industry'] == industry]
    return res

def img1(data):
        p1 = data.loc[:,["total_employees","rating"]].groupby("rating").count()
        ind =p1.index
        val = list(map(int,p1.values))
        plt.figure(dpi = 200)
        plt.bar(ind,val,color=["m","c","r","g"])
        ticks = plt.xticks()
        for i in range(len(ticks[0])):
            plt.text(ticks[0][i],val[i],val[i])
        plt.xlabel ("Rating",size = 20)
        plt.ylabel("Count",size = 20)
        plt.savefig("image.png")
        return 

def img2(data):
        p2 = data["old"].apply(lambda x:int(x.split(" ")[1]))
        limit =  (round(p2.max(),-1) )+ 10
        bins = list(range(0,limit+1,10))
        labels = []
        for i in range(0,limit-9,10):
                labels.append(f"{i}-{i+10}")
        p2 = pd.cut(p2,bins,labels=labels)
        p2 = pd.DataFrame({"old":p2.values,"n":np.full(len(p2.values),fill_value = 1 )})  
        p2 = p2.groupby(by = "old").count()
        ind =p2.index
        val = list(map(int,p2.values))
        plt.figure(figsize = (15,4),dpi = 200)
        plt.bar(ind,val,color=["m","c","r","g"])
        ticks = plt.xticks()
        for i in range(len(ticks[0])):
                plt.text(ticks[0][i],val[i],val[i])
        plt.xlabel ("Old",size = 20)
        plt.ylabel("Count",size = 20)
        plt.savefig("image2.png")
        plt.show()  
        return

Overwriting methods.py

In [140]:
import methods