In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
import os

In [7]:
os.getcwd()

'F:\\Study (E)\\Data Science\\Grras\\Projects\\Job Seeker (Ambition box)'

In [1370]:
os.chdir('F:\\Study (E)\\Data Science\\Grras\\Projects\\Job Seeker (Ambition box)\\Ambition Box Data (Uncleaned Data)\\')

In [1373]:
data1 = pd.read_csv("chennai.csv")
data1

,Unnamed: 0,company_name,company_rating,other_data
0,0,TCS,3.8,"IT Services & Consulting , 1 Lakh+ Employees ,..."
1,1,Cognizant,3.9,"IT Services & Consulting , 1 Lakh+ Employees ,..."
2,2,HCLTech,3.7,"IT Services & Consulting , 1 Lakh+ Employees ,..."
3,3,Accenture,4.0,"IT Services & Consulting , 1 Lakh+ Employees ,..."
4,4,Wipro,3.8,"IT Services & Consulting , 1 Lakh+ Employees ,..."
...,...,...,...,...
9995,9995,Thulirsoftware Technologies,4.4,Chennai +1 more
9996,9996,B-FLUX MANAGEMENT SERVICES,2.7,"11-50 Employees (Global) , 13 years old , Chen..."
9997,9997,Nexus,4.1,"Internet , 24 years old , Chennai +12 more"
9998,9998,Bharathi Matriculation Higher Secondary School,3.3,"Education & Training , 11-50 Employees , Chenn..."
9999,9999,Thiru Arooran Sugars,3.1,"501-1k Employees , Public , 70 years old , Che..."

In [1375]:
data1.columns

Index(['Unnamed: 0', 'company_name', 'company_rating', 'other_data'], dtype='object')

In [1377]:
data1.drop("Unnamed: 0",axis=1,inplace = True)
data1

,company_name,company_rating,other_data
0,TCS,3.8,"IT Services & Consulting , 1 Lakh+ Employees ,..."
1,Cognizant,3.9,"IT Services & Consulting , 1 Lakh+ Employees ,..."
2,HCLTech,3.7,"IT Services & Consulting , 1 Lakh+ Employees ,..."
3,Accenture,4.0,"IT Services & Consulting , 1 Lakh+ Employees ,..."
4,Wipro,3.8,"IT Services & Consulting , 1 Lakh+ Employees ,..."
...,...,...,...
9995,Thulirsoftware Technologies,4.4,Chennai +1 more
9996,B-FLUX MANAGEMENT SERVICES,2.7,"11-50 Employees (Global) , 13 years old , Chen..."
9997,Nexus,4.1,"Internet , 24 years old , Chennai +12 more"
9998,Bharathi Matriculation Higher Secondary School,3.3,"Education & Training , 11-50 Employees , Chenn..."
9999,Thiru Arooran Sugars,3.1,"501-1k Employees , Public , 70 years old , Che..."

In [1380]:
others_data1= pd.DataFrame({
            "others_data":data1.iloc[:,-1].apply(lambda x:x.split(","))})
others_data1

                                            others_data
0     [IT Services & Consulting ,  1 Lakh+ Employees...
1     [IT Services & Consulting ,  1 Lakh+ Employees...
2     [IT Services & Consulting ,  1 Lakh+ Employees...
3     [IT Services & Consulting ,  1 Lakh+ Employees...
4     [IT Services & Consulting ,  1 Lakh+ Employees...
...                                                 ...
9995                                  [Chennai +1 more]
9996  [11-50 Employees (Global) ,  13 years old ,  C...
9997     [Internet ,  24 years old ,  Chennai +12 more]
9998  [Education & Training ,  11-50 Employees ,  Ch...
9999  [501-1k Employees ,  Public ,  70 years old , ...

[10000 rows x 1 columns]

In [1383]:
type(others_data1)

pandas.core.frame.DataFrame

In [1386]:
indus_s = set()
def old(x):
    len_x = len(x)
    for i in range(len_x):
        if "years" in x[i]:
            return x[i]
    else:
        return np.nan

In [1388]:
others_data1 = others_data1.assign(
old = others_data1.loc[:,"others_data"].apply(old)
                                  )
others_data1

                                            others_data             old
0     [IT Services & Consulting ,  1 Lakh+ Employees...   56 years old
1     [IT Services & Consulting ,  1 Lakh+ Employees...   30 years old
2     [IT Services & Consulting ,  1 Lakh+ Employees...   33 years old
3     [IT Services & Consulting ,  1 Lakh+ Employees...   35 years old
4     [IT Services & Consulting ,  1 Lakh+ Employees...   79 years old
...                                                 ...             ...
9995                                  [Chennai +1 more]             NaN
9996  [11-50 Employees (Global) ,  13 years old ,  C...   13 years old
9997     [Internet ,  24 years old ,  Chennai +12 more]   24 years old
9998  [Education & Training ,  11-50 Employees ,  Ch...             NaN
9999  [501-1k Employees ,  Public ,  70 years old , ...   70 years old

[10000 rows x 2 columns]

In [1391]:
index = others_data1[~(others_data1["old"].isna())]
index

                                            others_data             old
0     [IT Services & Consulting ,  1 Lakh+ Employees...   56 years old
1     [IT Services & Consulting ,  1 Lakh+ Employees...   30 years old
2     [IT Services & Consulting ,  1 Lakh+ Employees...   33 years old
3     [IT Services & Consulting ,  1 Lakh+ Employees...   35 years old
4     [IT Services & Consulting ,  1 Lakh+ Employees...   79 years old
...                                                 ...             ...
9992                  [19 years old ,  Chennai +3 more]   19 years old
9994  [FinTech ,  51-200 Employees (Global) ,  19 ye...   19 years old
9996  [11-50 Employees (Global) ,  13 years old ,  C...   13 years old
9997     [Internet ,  24 years old ,  Chennai +12 more]   24 years old
9999  [501-1k Employees ,  Public ,  70 years old , ...   70 years old

[5562 rows x 2 columns]

In [1394]:
def rem_years(x):
    len_x = len(x)
    for i in range(len_x):
        if "years" in x[i]:
            return x[:i]+x[i+1:]

In [1396]:
others_data1["others_data"] = pd.concat((index["others_data"].apply(rem_years),others_data1[others_data1["old"].isna()]["others_data"]),axis = 0)
others_data1["others_data"]

0       [IT Services & Consulting ,  1 Lakh+ Employees...
1       [IT Services & Consulting ,  1 Lakh+ Employees...
2       [IT Services & Consulting ,  1 Lakh+ Employees...
3       [IT Services & Consulting ,  1 Lakh+ Employees...
4       [IT Services & Consulting ,  1 Lakh+ Employees...
                              ...
9995                                    [Chennai +1 more]
9996        [11-50 Employees (Global) ,  Chennai +1 more]
9997                       [Internet ,  Chennai +12 more]
9998    [Education & Training ,  11-50 Employees ,  Ch...
9999      [501-1k Employees ,  Public ,  Chennai +3 more]
Name: others_data, Length: 10000, dtype: object

In [1398]:
others_data1

                                            others_data             old
0     [IT Services & Consulting ,  1 Lakh+ Employees...   56 years old
1     [IT Services & Consulting ,  1 Lakh+ Employees...   30 years old
2     [IT Services & Consulting ,  1 Lakh+ Employees...   33 years old
3     [IT Services & Consulting ,  1 Lakh+ Employees...   35 years old
4     [IT Services & Consulting ,  1 Lakh+ Employees...   79 years old
...                                                 ...             ...
9995                                  [Chennai +1 more]             NaN
9996      [11-50 Employees (Global) ,  Chennai +1 more]   13 years old
9997                     [Internet ,  Chennai +12 more]   24 years old
9998  [Education & Training ,  11-50 Employees ,  Ch...             NaN
9999    [501-1k Employees ,  Public ,  Chennai +3 more]   70 years old

[10000 rows x 2 columns]

In [1400]:
def employees(x):
    len_x = len(x)
    for i in range(len_x):
        if "employees" in x[i].lower():
            return x[i]
    else:
        return np.nan

In [1401]:
others_data1 = others_data1.assign(
total_employees = others_data1.loc[:,"others_data"].apply(employees)
                                )
others_data1

,others_data,old,total_employees
0,"[IT Services & Consulting , 1 Lakh+ Employees...",56 years old,1 Lakh+ Employees
1,"[IT Services & Consulting , 1 Lakh+ Employees...",30 years old,1 Lakh+ Employees
2,"[IT Services & Consulting , 1 Lakh+ Employees...",33 years old,1 Lakh+ Employees
3,"[IT Services & Consulting , 1 Lakh+ Employees...",35 years old,1 Lakh+ Employees
4,"[IT Services & Consulting , 1 Lakh+ Employees...",79 years old,1 Lakh+ Employees
...,...,...,...
9995,[Chennai +1 more],NaN,NaN
9996,"[11-50 Employees (Global) , Chennai +1 more]",13 years old,11-50 Employees (Global)
9997,"[Internet , Chennai +12 more]",24 years old,NaN
9998,"[Education & Training , 11-50 Employees , Ch...",NaN,11-50 Employees
9999,"[501-1k Employees , Public , Chennai +3 more]",70 years old,501-1k Employees

In [1402]:
def remove_employ(x):
    len_x = len(x)
    for i in range(len_x):
        if "employees" in x[i].lower():
            return x[:i]+x[i+1:]
    else:
        return x

In [1406]:
others_data1["others_data"] = others_data1["others_data"].apply(remove_employ)
others_data1["others_data"]

0       [IT Services & Consulting ,  Public ,  Chennai...
1       [IT Services & Consulting ,  Forbes Global 200...
2       [IT Services & Consulting ,  Public ,  Chennai...
3       [IT Services & Consulting ,  Public ,  Chennai...
4       [IT Services & Consulting ,  Public ,  Chennai...
                              ...
9995                                    [Chennai +1 more]
9996                                   [ Chennai +1 more]
9997                       [Internet ,  Chennai +12 more]
9998            [Education & Training ,  Chennai +5 more]
9999                         [ Public ,  Chennai +3 more]
Name: others_data, Length: 10000, dtype: object

In [1411]:
others_data1

,others_data,old,total_employees
0,"[IT Services & Consulting , Public , Chennai...",56 years old,1 Lakh+ Employees
1,"[IT Services & Consulting , Forbes Global 200...",30 years old,1 Lakh+ Employees
2,"[IT Services & Consulting , Public , Chennai...",33 years old,1 Lakh+ Employees
3,"[IT Services & Consulting , Public , Chennai...",35 years old,1 Lakh+ Employees
4,"[IT Services & Consulting , Public , Chennai...",79 years old,1 Lakh+ Employees
...,...,...,...
9995,[Chennai +1 more],NaN,NaN
9996,[ Chennai +1 more],13 years old,11-50 Employees (Global)
9997,"[Internet , Chennai +12 more]",24 years old,NaN
9998,"[Education & Training , Chennai +5 more]",NaN,11-50 Employees
9999,"[ Public , Chennai +3 more]",70 years old,501-1k Employees

In [1415]:
city = set()
def cities(x):
    len_x = len(x)
    for i in range(len_x):
        if "+" in x[i] or x[i].strip().lower() in city:
            city.add(x[i].split("+")[0].strip().lower())
            return x[i]
    else:
        return np.nan

In [1417]:
others_data1 = others_data1.assign(
cities = others_data1.loc[:,"others_data"].apply(cities)
                                )
others_data1

C:\Users\DELL\AppData\Roaming\Python\Python312\site-packages\IPython\core\displayhook.py:281: UserWarning: Output cache limit (currently 1000 entries) hit.
Flushing oldest 200 entries.
  warn('Output cache limit (currently {sz} entries) hit.\n'

,others_data,old,total_employees,cities
0,"[IT Services & Consulting , Public , Chennai...",56 years old,1 Lakh+ Employees,Chennai +349 more
1,"[IT Services & Consulting , Forbes Global 200...",30 years old,1 Lakh+ Employees,Chennai +169 more
2,"[IT Services & Consulting , Public , Chennai...",33 years old,1 Lakh+ Employees,Chennai +184 more
3,"[IT Services & Consulting , Public , Chennai...",35 years old,1 Lakh+ Employees,Chennai +181 more
4,"[IT Services & Consulting , Public , Chennai...",79 years old,1 Lakh+ Employees,Chennai +272 more
...,...,...,...,...
9995,[Chennai +1 more],NaN,NaN,Chennai +1 more
9996,[ Chennai +1 more],13 years old,11-50 Employees (Global),Chennai +1 more
9997,"[Internet , Chennai +12 more]",24 years old,NaN,Chennai +12 more
9998,"[Education & Training , Chennai +5 more]",NaN,11-50 Employees,Chennai +5 more
9999,"[ Public , Chennai +3 more]",70 years old,501-1k Employees,Chennai +3 more

In [1420]:
def remove_cities(x):
    len_x = len(x)
    for i in range(len_x):
        if x[i].lower().strip() in city or "+" in x[i] :
            return x[:i]+x[i+1:]
    return x

In [1421]:
others_data1["others_data"] = others_data1["others_data"].apply(remove_cities)
others_data1["others_data"]

0                   [IT Services & Consulting ,  Public ]
1       [IT Services & Consulting ,  Forbes Global 2000 ]
2                   [IT Services & Consulting ,  Public ]
3                   [IT Services & Consulting ,  Public ]
4                   [IT Services & Consulting ,  Public ]
                              ...
9995                                                   []
9996                                                   []
9997                                          [Internet ]
9998                              [Education & Training ]
9999                                           [ Public ]
Name: others_data, Length: 10000, dtype: object

In [1425]:
others_data1

,others_data,old,total_employees,cities
0,"[IT Services & Consulting , Public ]",56 years old,1 Lakh+ Employees,Chennai +349 more
1,"[IT Services & Consulting , Forbes Global 2000 ]",30 years old,1 Lakh+ Employees,Chennai +169 more
2,"[IT Services & Consulting , Public ]",33 years old,1 Lakh+ Employees,Chennai +184 more
3,"[IT Services & Consulting , Public ]",35 years old,1 Lakh+ Employees,Chennai +181 more
4,"[IT Services & Consulting , Public ]",79 years old,1 Lakh+ Employees,Chennai +272 more
...,...,...,...,...
9995,[],NaN,NaN,Chennai +1 more
9996,[],13 years old,11-50 Employees (Global),Chennai +1 more
9997,[Internet ],24 years old,NaN,Chennai +12 more
9998,[Education & Training ],NaN,11-50 Employees,Chennai +5 more
9999,[ Public ],70 years old,501-1k Employees,Chennai +3 more

In [1428]:
ty = ["public","forbes global 2000", "conglomerate", "startup","fortune global 500","fortune india 500","fortune us 500", "indian unicorn", "government"]
def typ(x):
    len_x = len(x)
    for i in range(len_x):
        if x[i].strip().lower() in ty:
            return x[i]
    else:
        return np.nan

In [1430]:
others_data1 = others_data1.assign(
type = others_data1.loc[:,"others_data"].apply(typ)
                                )
others_data1

,others_data,old,total_employees,cities,type
0,"[IT Services & Consulting , Public ]",56 years old,1 Lakh+ Employees,Chennai +349 more,Public
1,"[IT Services & Consulting , Forbes Global 2000 ]",30 years old,1 Lakh+ Employees,Chennai +169 more,Forbes Global 2000
2,"[IT Services & Consulting , Public ]",33 years old,1 Lakh+ Employees,Chennai +184 more,Public
3,"[IT Services & Consulting , Public ]",35 years old,1 Lakh+ Employees,Chennai +181 more,Public
4,"[IT Services & Consulting , Public ]",79 years old,1 Lakh+ Employees,Chennai +272 more,Public
...,...,...,...,...,...
9995,[],NaN,NaN,Chennai +1 more,NaN
9996,[],13 years old,11-50 Employees (Global),Chennai +1 more,NaN
9997,[Internet ],24 years old,NaN,Chennai +12 more,NaN
9998,[Education & Training ],NaN,11-50 Employees,Chennai +5 more,NaN
9999,[ Public ],70 years old,501-1k Employees,Chennai +3 more,Public

In [1433]:
ty = ["public","forbes global 2000", "conglomerate", "startup","fortune global 500","fortune india 500","fortune us 500", "indian unicorn", "government"]
def remove_typ(x):
    len_x = len(x)
    for i in range(len_x):
        if x[i].strip().lower() in ty:
            return x[:i]+x[i+1:]
    else:
        return []

In [1435]:
others_data1["others_data"] = others_data1["others_data"].apply(remove_typ)
others_data1["others_data"]

0       [IT Services & Consulting ]
1       [IT Services & Consulting ]
2       [IT Services & Consulting ]
3       [IT Services & Consulting ]
4       [IT Services & Consulting ]
                   ...
9995                             []
9996                             []
9997                             []
9998                             []
9999                             []
Name: others_data, Length: 10000, dtype: object

In [1438]:
others_data1

,others_data,old,total_employees,cities,type
0,[IT Services & Consulting ],56 years old,1 Lakh+ Employees,Chennai +349 more,Public
1,[IT Services & Consulting ],30 years old,1 Lakh+ Employees,Chennai +169 more,Forbes Global 2000
2,[IT Services & Consulting ],33 years old,1 Lakh+ Employees,Chennai +184 more,Public
3,[IT Services & Consulting ],35 years old,1 Lakh+ Employees,Chennai +181 more,Public
4,[IT Services & Consulting ],79 years old,1 Lakh+ Employees,Chennai +272 more,Public
...,...,...,...,...,...
9995,[],NaN,NaN,Chennai +1 more,NaN
9996,[],13 years old,11-50 Employees (Global),Chennai +1 more,NaN
9997,[],24 years old,NaN,Chennai +12 more,NaN
9998,[],NaN,11-50 Employees,Chennai +5 more,NaN
9999,[],70 years old,501-1k Employees,Chennai +3 more,Public

In [1441]:
def indus(x):
    if x == []:
        return np.nan
    return x[0]

In [1443]:
others_data1 = others_data1.assign(
industry = others_data1.loc[:,"others_data"].apply(indus)
                                )
others_data1

,others_data,old,total_employees,cities,type,industry
0,[IT Services & Consulting ],56 years old,1 Lakh+ Employees,Chennai +349 more,Public,IT Services & Consulting
1,[IT Services & Consulting ],30 years old,1 Lakh+ Employees,Chennai +169 more,Forbes Global 2000,IT Services & Consulting
2,[IT Services & Consulting ],33 years old,1 Lakh+ Employees,Chennai +184 more,Public,IT Services & Consulting
3,[IT Services & Consulting ],35 years old,1 Lakh+ Employees,Chennai +181 more,Public,IT Services & Consulting
4,[IT Services & Consulting ],79 years old,1 Lakh+ Employees,Chennai +272 more,Public,IT Services & Consulting
...,...,...,...,...,...,...
9995,[],NaN,NaN,Chennai +1 more,NaN,NaN
9996,[],13 years old,11-50 Employees (Global),Chennai +1 more,NaN,NaN
9997,[],24 years old,NaN,Chennai +12 more,NaN,NaN
9998,[],NaN,11-50 Employees,Chennai +5 more,NaN,NaN
9999,[],70 years old,501-1k Employees,Chennai +3 more,Public,NaN

In [1445]:
others_data = others_data1.drop(labels = "others_data",axis =1)
others_data

,old,total_employees,cities,type,industry
0,56 years old,1 Lakh+ Employees,Chennai +349 more,Public,IT Services & Consulting
1,30 years old,1 Lakh+ Employees,Chennai +169 more,Forbes Global 2000,IT Services & Consulting
2,33 years old,1 Lakh+ Employees,Chennai +184 more,Public,IT Services & Consulting
3,35 years old,1 Lakh+ Employees,Chennai +181 more,Public,IT Services & Consulting
4,79 years old,1 Lakh+ Employees,Chennai +272 more,Public,IT Services & Consulting
...,...,...,...,...,...
9995,NaN,NaN,Chennai +1 more,NaN,NaN
9996,13 years old,11-50 Employees (Global),Chennai +1 more,NaN,NaN
9997,24 years old,NaN,Chennai +12 more,NaN,NaN
9998,NaN,11-50 Employees,Chennai +5 more,NaN,NaN
9999,70 years old,501-1k Employees,Chennai +3 more,Public,NaN

In [1448]:
data1 = pd.concat([data1.iloc[:,:2],others_data1.iloc[:,1:]],axis=1)
data1

,company_name,company_rating,old,total_employees,cities,type,industry
0,TCS,3.8,56 years old,1 Lakh+ Employees,Chennai +349 more,Public,IT Services & Consulting
1,Cognizant,3.9,30 years old,1 Lakh+ Employees,Chennai +169 more,Forbes Global 2000,IT Services & Consulting
2,HCLTech,3.7,33 years old,1 Lakh+ Employees,Chennai +184 more,Public,IT Services & Consulting
3,Accenture,4.0,35 years old,1 Lakh+ Employees,Chennai +181 more,Public,IT Services & Consulting
4,Wipro,3.8,79 years old,1 Lakh+ Employees,Chennai +272 more,Public,IT Services & Consulting
...,...,...,...,...,...,...,...
9995,Thulirsoftware Technologies,4.4,NaN,NaN,Chennai +1 more,NaN,NaN
9996,B-FLUX MANAGEMENT SERVICES,2.7,13 years old,11-50 Employees (Global),Chennai +1 more,NaN,NaN
9997,Nexus,4.1,24 years old,NaN,Chennai +12 more,NaN,NaN
9998,Bharathi Matriculation Higher Secondary School,3.3,NaN,11-50 Employees,Chennai +5 more,NaN,NaN
9999,Thiru Arooran Sugars,3.1,70 years old,501-1k Employees,Chennai +3 more,Public,NaN

In [1451]:
os.getcwd()

'F:\\Study (E)\\Data Science\\Grras\\Projects\\Job Seeker (Ambition box)\\Ambition Box Data (Uncleaned Data)'

In [1454]:
os.chdir("F:\\Study (E)\\Data Science\\Grras\\Projects\\Job Seeker (Ambition box)\\")

In [1457]:
os.mkdir("F:\\Study (E)\\Data Science\\Grras\\Projects\\Job Seeker (Ambition box)\\Ambition Box Data (Cleaned Data)")

FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'F:\\Study (E)\\Data Science\\Grras\\Projects\\Job Seeker (Ambition box)\\Ambition Box Data (Cleaned Data)'

In [11]:
os.chdir("F:\\Study (E)\\Data Science\\Grras\\Projects\\Job Seeker (Ambition box)\\Ambition Box Data (Cleaned Data)")

In [1463]:
g = data1.to_csv()
g

',company_name,company_rating,old,total_employees,cities,type,industry\r\n0,TCS,3.8, 56 years old , 1 Lakh+ Employees , Chennai +349 more, Public ,IT Services & Consulting \r\n1,Cognizant,3.9, 30 years old , 1 Lakh+ Employees , Chennai +169 more, Forbes Global 2000 ,IT Services & Consulting \r\n2,HCLTech,3.7, 33 years old , 1 Lakh+ Employees , Chennai +184 more, Public ,IT Services & Consulting \r\n3,Accenture,4.0, 35 years old , 1 Lakh+ Employees , Chennai +181 more, Public ,IT Services & Consulting \r\n4,Wipro,3.8, 79 years old , 1 Lakh+ Employees , Chennai +272 more, Public ,IT Services & Consulting \r\n5,Infosys,3.8, 43 years old , 1 Lakh+ Employees , Chennai +182 more, Public ,IT Services & Consulting \r\n6,Capgemini,3.8, 57 years old , 1 Lakh+ Employees , Chennai +142 more, Public ,IT Services & Consulting \r\n7,Sutherland Global Services,3.7, 38 years old , 10k-50k Employees , Chennai +57 more,,\r\n8,Larsen & Toubro Limited,4.1, 86 years old , 10k-50k Employees , Chennai +623 more, Public ,Engineering & Construction \r\n9,Hexaware Technologies,3.7, 34 years old , 10k-50k Employees , Chennai +46 more, Fortune India 500 ,IT Services & Consulting \r\n10,Tech Mahindra,3.7, 38 years old , 1 Lakh+ Employees , Chennai +269 more, Public ,IT Services & Consulting \r\n11,Amazon,4.1, 30 years old , 1 Lakh+ Employees , Chennai +455 more, Public ,Internet \r\n12,Standard Chartered,3.9, 171 years old , 10k-50k Employees , Chennai +58 more, Fortune India 500 ,Banking \r\n13,Access Healthcare,4.0, 13 years old , 5k-10k Employees , Chennai +31 more,,\r\n14,Hyundai Motor India Limited,4.4, 57 years old , 10k-50k Employees , Chennai +263 more, Fortune India 500 ,Automobile \r\n15,Ford Motor,4.5, 121 years old , 5k-10k Employees , Chennai +110 more, Public ,Automobile \r\n16,HCL Group,3.8, 48 years old , 1 Lakh+ Employees , Chennai +74 more,,\r\n17,IBM,4.1, 113 years old , 1 Lakh+ Employees , Chennai +149 more, Public ,IT Services & Consulting \r\n18,Teleperformance,3.8, 46 years old , 50k-1 Lakh Employees , Chennai +192 more, Forbes Global 2000 ,BPO \r\n19,HDFC Bank,4.0, 30 years old , 1 Lakh+ Employees , Chennai +1560 more, Public ,Banking \r\n20,BNY Mellon,4.0, 20 years old , 10k-50k Employees , Chennai +16 more, Forbes Global 2000 ,Investment Banking / Venture Capital / Private Equity \r\n21,Omega Healthcare,3.8, 21 years old , 10k-50k Employees , Chennai +48 more,,\r\n22,Royal Enfield,4.3, 123 years old , 5k-10k Employees , Chennai +308 more,,\r\n23,Flex,4.1, 55 years old , 5k-10k Employees , Chennai +39 more, Forbes Global 2000 ,Logistics \r\n24,ICICI Bank,4.0, 30 years old , 1 Lakh+ Employees , Chennai +1295 more, Public ,Banking \r\n25,Movate,3.4, 28 years old , 1k-5k Employees , Chennai +29 more,,\r\n26,HDB Financial Services,4.0, 17 years old , 1 Lakh+ Employees , Chennai +959 more,,\r\n27,Renault Nissan Technology & Business Centre India,3.9, 17 years old , 5k-10k Employees , Chennai +13 more,,\r\n28,AGS Health,4.0, 13 years old , 10k-50k Employees , Chennai +39 more,,\r\n29,DXC Technology,3.8, 7 years old , 10k-50k Employees , Chennai +83 more, Public ,IT Services & Consulting \r\n30,R.R. Donnelley,4.0, 160 years old , 5k-10k Employees , Chennai +12 more,,\r\n31,Renault-Nissan,4.1, 17 years old , 10k-50k Employees , Chennai +74 more,,\r\n32,Ashok Leyland,4.1, 76 years old , 5k-10k Employees , Chennai +216 more, Public ,Automobile \r\n33,Virtusa Consulting Services,3.8, 28 years old , 10k-50k Employees , Chennai +39 more,,\r\n34,CAMS,3.7, 36 years old , 5k-10k Employees , Chennai +89 more,,\r\n35,L&T Construction,4.1, 80 years old , 5k-10k Employees , Chennai +360 more, Public ,Engineering & Construction \r\n36,Straive,3.5, 44 years old , 10k-50k Employees , Chennai +23 more,,\r\n37,NTT DATA,4.0, 36 years old , 10k-50k Employees , Chennai +60 more,,\r\n38,Photon Interactive,4.0, 25 years old , 1k-5k Employees , Chennai +11 more,,\r\n39,MRF Tyres,3.8, 78 years old , 10k-50k Employees , Chennai +161 more, Public ,Auto Components \r\n40,MiraMed Ajuba,4.0, 23 years old , 1k-5k Employees , Chennai +14 more,,\r\n41,Maersk,4.3, 120 years old , 10k-50k Employees , Chennai +36 more,,\r\n42,LTIMindtree,3.6, 27 years old , 50k-1 Lakh Employees , Chennai +52 more, Public ,IT Services & Consulting \r\n43,iOPEX Technologies,3.7, 15 years old , 1k-5k Employees , Chennai +14 more,,\r\n44,Statestreet HCL Services,3.3, 12 years old , 5k-10k Employees , Chennai +16 more,,\r\n45,NatWest Group,4.1,, 10k-50k Employees , Chennai +21 more, Forbes Global 2000 ,Banking \r\n46,Lucas-TVS,4.0, 63 years old , 5k-10k Employees , Chennai +60 more,,\r\n47,Allsec Technologies,4.0, 24 years old , 1k-5k Employees , Chennai +26 more, Public ,BPO \r\n48,Mahindra & Mahindra,4.2, 79 years old , 1 Lakh+ Employees , Chennai +480 more, Public ,Automobile \r\n49,First Source,3.8, 23 years old , 10k-50k Employees , Chennai +55 more, Public ,BPO \r\n50,Delphi TVS,4.1, 35 years old , 1k-5k Employees , Chennai +38 more,,\r\n51,Atos Syntel,3.6, 44 years old , 5k-10k Employees , Chennai +25 more,,\r\n52,L&T Infotech,3.8, 28 years old , 10k-50k Employees , Chennai +84 more, Public ,IT Services & Consulting \r\n53,Intellect Design Arena,4.1, 13 years old , 5k-10k Employees , Chennai +26 more, Public ,FinTech \r\n54,Zoho,4.3, 28 years old , 10k-50k Employees , Chennai +26 more,,\r\n55,HTC Global Services,3.6, 34 years old , 5k-10k Employees , Chennai +25 more,,\r\n56,Daimler India Commercial Vehicles,4.2, 138 years old , 1k-5k Employees , Chennai +39 more,,\r\n57,Hewlett Packard Enterprise,4.3, 9 years old , 10k-50k Employees , Chennai +85 more, Forbes Global 2000 ,IT Services & Consulting \r\n58,Equitas Small Finance Bank,4.4, 17 years old , 10k-50k Employees , Chennai +368 more, Fortune India 500 ,Banking \r\n59,Apollo Hospitals,4.2, 41 years old , 10k-50k Employees , Chennai +189 more, Public ,Healthcare \r\n60,Valeo,4.1, 101 years old , 5k-10k Employees , Chennai +19 more, Forbes Global 2000 ,Auto Components \r\n61,Barclays,4.0, 334 years old , 10k-50k Employees , Chennai +30 more, Forbes Global 2000 ,Banking \r\n62,Shell,4.3, 117 years old , 10k-50k Employees , Chennai +73 more, Public ,Oil & Gas \r\n63,Mando Automotive,3.9, 18 years old , 1k-5k Employees , Chennai +18 more, Fortune India 500 ,Auto Components \r\n64,Brakes India,4.1, 62 years old , 501-1k Employees , Chennai +74 more, Fortune India 500 ,Auto Components \r\n65,Mphasis,3.5, 26 years old , 10k-50k Employees , Chennai +54 more, Public ,IT Services & Consulting \r\n66,Aspire Systems,4.0, 28 years old , 1k-5k Employees , Chennai +17 more,,\r\n67,Amazon Development Centre India,4.2,, 10k-50k Employees , Chennai +84 more,,\r\n68,Verizon,4.2, 24 years old , 5k-10k Employees , Chennai +10 more, Forbes Global 2000 ,Telecom \r\n69,Vestas,4.3, 27 years old , 1k-5k Employees , Chennai +43 more, Forbes Global 2000 ,Power \r\n70,TVS Sundram Fasteners,3.8, 62 years old , 1k-5k Employees , Chennai +42 more, Public ,Auto Components \r\n71,Axis Bank,3.9, 31 years old , 50k-1 Lakh Employees , Chennai +1317 more, Public ,Banking \r\n72,Episource,3.9, 18 years old , 1k-5k Employees , Chennai +13 more,,\r\n73,BNP Paribas,3.9, 176 years old , 10k-50k Employees , Chennai +22 more, Forbes Global 2000 ,Financial Services \r\n74,ZF Commercial Vehicle Control Systems,4.0,,, Chennai +32 more,,\r\n75,Infosys BPM,3.8, 22 years old , 10k-50k Employees , Pune +68 more,,\r\n76,FLSmidth,3.7, 142 years old , 1k-5k Employees , Chennai +19 more,,\r\n77,IndusInd Bank,3.7, 30 years old , 10k-50k Employees , Mumbai +689 more, Public ,Banking \r\n78,Bharti Airtel,4.1, 29 years old , 10k-50k Employees , Gurgaon / Gurugram +660 more, Public ,Telecom \r\n79,Prodapt,3.8, 25 years old , 1k-5k Employees , Chennai +12 more,,\r\n80,Apollo Tyres,4.1, 52 years old , 5k-10k Employees , Chennai +152 more, Public ,Auto Components \r\n81,Prochant,4.4, 25 years old , 1k-5k Employees , Chennai +7 more,,\r\n82,KaaShiv InfoTech Company,4.9,, 51-200 Employees , Chennai +4 more,,\r\n83,BYJU\'S,3.1, 13 years old , 10k-50k Employees , Chennai +307 more, Indian Unicorn ,EdTech \r\n84,CMA CGM,4.0, 46 years old , 501-1k Employees , Chennai +24 more,,\r\n85,KONE,4.3, 114 years old , 5k-10k Employees , Chennai +65 more, Forbes Global 2000 ,Industrial Machinery \r\n86,L&T Technology Services,3.4, 12 years old , 10k-50k Employees , Chennai +52 more, Public ,IT Services & Consulting \r\n87,Citicorp,3.7, 27 years old , 10k-50k Employees , Chennai +23 more,,\r\n88,Foxconn,4.1, 50 years old , 10k-50k Employees , Chennai +40 more,,\r\n89,Exela Technologies,3.6, 13 years old , 1k-5k Employees , Chennai +20 more,,\r\n90,Sundaram Clayton,4.1, 62 years old , 1k-5k Employees , Chennai +24 more, Public ,Auto Components \r\n91,Ramco Systems,3.5, 27 years old , 1k-5k Employees , Chennai +23 more, Public ,Software Product \r\n92,UST,3.8, 23 years old , 10k-50k Employees , Chennai +36 more,,\r\n93,BGR Energy Systems,3.9, 39 years old , 1k-5k Employees , Chennai +49 more, Public ,Engineering & Construction \r\n94,Barclays Shared Services,4.1, 17 years old , 5k-10k Employees , Chennai +12 more,,\r\n95,ACTE,4.8, 13 years old , 1-10 Employees , Chennai +10 more,,\r\n96,TNQ Technologies,3.6, 26 years old , 1k-5k Employees , Chennai +9 more,,\r\n97,Tractors and Farm Equipment,4.1, 64 years old , 10k-50k Employees , Chennai +163 more, Public ,Industrial Machinery \r\n98,AstraZeneca,4.2, 25 years old , 501-1k Employees , Chennai +40 more, Public ,Pharma \r\n99,FIS,3.9, 56 years old , 10k-50k Employees , Chennai +43 more,,\r\n100,Wells Fargo,4.0, 172 years old , 10k-50k Employees , Chennai +21 more, Public ,Financial Services \r\n101,Ford Business Solutions,4.5, 26 years old , 10k-50k Employees , Chennai +42 more,,\r\n102,Metriqe Solutions,4.3, 17 years old , 201-500 Employees , Chennai +2 more,,\r\n103,Kotak Mahindra Bank,3.9, 21 years old , 50k-1 Lakh Employees , Chennai +573 more, Public ,Banking \r\n104,Reliance Retail,4.0, 18 years old , 1 Lakh+ Employees , Chennai +1013 more,,\r\n105,Tata Communications,4.1, 38 years old , 5k-10k Employees , Chennai +86 more, Public ,Telecom \r\n106,Yamaha Motor,4.2, 69 years old , 1k-5k Employees , Chennai +121 more, Fortune India 500 ,Automobile \r\n107,Sify Technologies,4.0, 29 years old , 1k-5k Employees , Chennai +107 more,,\r\n108,TVS Supply Chain Solutions,4.0, 128 years old , 1k-5k Employees , Chennai +133 more,,\r\n109,Sheenlac Paints,4.6, 62 years old , 501-1k Employees , Chennai +146 more, Public ,Chemicals \r\n110,Societe Generale Global Solution Centre,3.9, 24 years old , 1k-5k Employees , Chennai +16 more,,\r\n111,Atos,3.8, 27 years old , 10k-50k Employees , Chennai +40 more, Forbes Global 2000 ,IT Services & Consulting \r\n112,Jio,4.0, 6 years old , 50k-1 Lakh Employees , Chennai +1175 more, Public ,Telecom \r\n113,Nokia Networks,4.3,, 501-1k Employees , Chennai +82 more,,\r\n114,Cavinkare,4.0, 41 years old , 1k-5k Employees , Chennai +147 more, Conglomerate ,FMCG \r\n115,Wheels,4.1, 62 years old , 1k-5k Employees , Chennai +35 more, Public ,Auto Components \r\n116,Caterpillar Inc,4.2, 99 years old , 5k-10k Employees , Chennai +34 more, Forbes Global 2000 ,Industrial Machinery \r\n117,CGI Group,4.1, 48 years old , 10k-50k Employees , Chennai +31 more, Forbes Global 2000 ,IT Services & Consulting \r\n118,Yes Bank,3.9, 20 years old , 10k-50k Employees , Chennai +447 more, Public ,Banking \r\n119,Bharat FIH,4.0,, 10k-50k Employees , Chennai +32 more,,\r\n120,Indium Software,4.2, 25 years old , 1k-5k Employees , Chennai +9 more,,\r\n121,Concentrix Corporation,3.9, 41 years old , 50k-1 Lakh Employees , Chennai +117 more, Public ,BPO \r\n122,Ernst & Young,3.6, 22 years old , 50k-1 Lakh Employees , Chennai +94 more,,\r\n123,Skill Lync,3.1, 9 years old , 1k-5k Employees , Chennai +13 more, Startup ,EdTech \r\n124,Samsung,4.1, 55 years old , 50k-1 Lakh Employees , Chennai +499 more, Public ,Consumer Electronics & Appliances \r\n125,Temenos,3.3, 31 years old , 1k-5k Employees , Chennai +8 more,,\r\n126,Star Health & Allied Insurance,3.9, 18 years old , 10k-50k Employees , Chennai +247 more, Fortune India 500 ,Insurance \r\n127,CorroHealth,3.4,,1k-5k Employees , Chennai +20 more,,\r\n128,Tube Investments of India,4.0, 75 years old , 1k-5k Employees , Chennai +53 more, Public ,Engineering & Construction \r\n129,Freshworks,3.7, 14 years old , 1k-5k Employees , Chennai +39 more, Public ,Software Product \r\n130,Casagrand,4.0, 20 years old , 501-1k Employees , Chennai +12 more,,\r\n131,Maveric Systems,3.7, 24 years old , 1k-5k Employees , Chennai +9 more, Public ,IT Services & Consulting \r\n132,BankBazaar,3.4, 16 years old , 1k-5k Employees , Chennai +11 more,,\r\n133,Sl Lumax,3.5, 27 years old , 1k-5k Employees , Chennai +13 more, Public ,Auto Components \r\n134,Nokia,4.2, 159 years old , 10k-50k Employees , Chennai +149 more, Forbes Global 2000 ,Telecom \r\n135,Citibank,4.0, 212 years old , 10k-50k Employees (Global) , Chennai +47 more, Fortune India 500 ,Banking \r\n136,WNS,3.5, 28 years old , 10k-50k Employees , Chennai +38 more,,\r\n137,Bank of America,4.4, 26 years old , 10k-50k Employees , Chennai +28 more, Fortune India 500 ,Banking \r\n138,Saipem,4.1, 67 years old , 1k-5k Employees , Chennai +37 more, Forbes Global 2000 ,Engineering & Construction \r\n139,Matrimony.com,4.4, 27 years old , 1k-5k Employees , Chennai +50 more, Public ,Internet \r\n140,Saint-Gobain,4.0, 359 years old , 10k-50k Employees , Chennai +92 more, Forbes Global 2000 ,Building Material \r\n141,TVS Credit,4.5, 16 years old , 10k-50k Employees , Chennai +312 more, Public ,NBFC \r\n142,Fujitsu,3.9, 89 years old , 5k-10k Employees , Chennai +29 more, Forbes Global 2000 ,IT Services & Consulting \r\n143,Cholamandalam Investment & Finance,4.1, 46 years old , 10k-50k Employees , Chennai +645 more, Fortune India 500 ,NBFC \r\n144,Sodexo,4.1, 16 years old , 10k-50k Employees , Chennai +131 more, Forbes Global 2000 ,Facility Management Services \r\n145,Zf Rane Automotive,4.1,, 1k-5k Employees , Chennai +44 more,,\r\n146,ICON Plc,4.2, 34 years old , 1k-5k Employees , Chennai +15 more, Public ,Clinical Research \r\n147,Lavender Technology,5.0, 14 years old , 5k-10k Employees , Chennai +4 more,,\r\n148,Avalon Technologies,3.9,, 1k-5k Employees , Chennai +14 more,,\r\n149,Bahwan CyberTek,3.9, 25 years old , 1k-5k Employees , Chennai +19 more,,\r\n150,Guardian India,4.1, 164 years old , 1k-5k Employees , Chennai +9 more,,\r\n151,Hyundai Mobis,3.9, 7 years old , 1k-5k Employees , Chennai +43 more, Forbes Global 2000 ,Auto Components \r\n152,Thryve Digital,4.1, 8 years old , 1k-5k Employees , Chennai +5 more,,\r\n153,CBRE,4.2, 118 years old , 10k-50k Employees , Chennai +75 more, Forbes Global 2000 ,Real Estate \r\n154,GAVS Technologies,3.9, 26 years old , 1k-5k Employees , Chennai +10 more,,\r\n155,Schneider Electric,4.2, 25 years old , 10k-50k Employees , Chennai +115 more, Forbes Global 2000 ,Industrial Automation \r\n156,Foundever,3.8, 39 years old , 5k-10k Employees , Chennai +16 more, Conglomerate ,BPO \r\n157,NextComm Corporation,4.9, 7 years old ,1k-5k Employees , Chennai +11 more,,\r\n158,Salcomp Manufacturing,4.2, 18 years old , 1k-5k Employees , Chennai +20 more,,\r\n159,Mindsprint,3.8, 17 years old , 1k-5k Employees , Chennai +6 more, Forbes Global 2000 ,IT Services & Consulting \r\n160,Imarque Solutions,3.6, 20 years old , 201-500 Employees , Chennai +12 more,,\r\n161,Tata Communications Transformation Services,4.1, 18 years old , 1k-5k Employees , Chennai +83 more,,\r\n162,Randstad,3.9, 32 years old , 5k-10k Employees , Chennai +264 more, Conglomerate ,Recruitment \r\n163,Altimetrik,3.8, 12 years old , 1k-5k Employees , Chennai +10 more,,\r\n164,RR,4.1,,,Chennai +11 more,,\r\n165,Voltech,3.7, 36 years old , 1k-5k Employees , Chennai +38 more,,\r\n166,Perficient,3.7, 27 years old , 1k-5k Employees , Chennai +10 more,,\r\n167,Pfizer,4.1, 20 years old , 1k-5k Employees , Chennai +113 more, Public ,Pharma \r\n168,Hinduja Global Solutions,4.0, 24 years old , 10k-50k Employees , Chennai +104 more, Public ,IT Services & Consulting \r\n169,Financial Software & Systems,3.8, 33 years old , 1k-5k Employees , Chennai +26 more,,\r\n170,Wipro Consumer Care & Lighting,3.9, 79 years old , 1k-5k Employees , Chennai +96 more,,\r\n171,ACT Fibernet,4.0, 16 years old , 5k-10k Employees , Chennai +42 more,,\r\n172,Deloitte,3.9, 179 years old , 1 Lakh+ Employees , Chennai +151 more,,\r\n173,Visteon,3.9, 24 years old , 1k-5k Employees , Chennai +15 more,,\r\n174,Diamondpick,4.1, 6 years old , 501-1k Employees , Chennai +7 more,,\r\n175,Scientific Publishing Services,3.9, 29 years old , 1k-5k Employees , Chennai +4 more,,\r\n176,Hatsun Agro Product,4.0, 54 years old , 5k-10k Employees , Chennai +101 more, Public ,Food Processing \r\n177,Capgemini Engineering,3.6,,10k-50k Employees , Chennai +21 more,,\r\n178,Samvardhana Motherson Group,3.8, 38 years old , 1k-5k Employees , Chennai +81 more, Public ,Auto Components \r\n179,Siemens Gamesa Renewable Power Private Limited,4.1, 48 years old , 1k-5k Employees , Chennai +56 more,,\r\n180,Philips,3.9, 94 years old , 5k-10k Employees , Chennai +84 more, Forbes Global 2000 ,Consumer Electronics & Appliances \r\n181,VA Tech Wabag,4.0, 100 years old , 501-1k Employees , Chennai +41 more, Public ,Waste Management \r\n182,HSBC Group,4.1, 159 years old , 10k-50k Employees , Chennai +59 more, Forbes Global 2000 ,Banking \r\n183,Vodafone Idea,4.2, 6 years old , 5k-10k Employees , Chennai +637 more, Public ,Telecom \r\n184,Fidelity Investments,4.3, 81 years old , 5k-10k Employees , Chennai +16 more,,\r\n185,Cholamandalam MS General Insurance,3.9, 23 years old , 1k-5k Employees , Chennai +324 more,,\r\n186,ITC,4.0, 114 years old , 10k-50k Employees , Chennai +301 more, Public ,FMCG \r\n187,Novac Technology Solutions,4.0, 18 years old , 1k-5k Employees , Chennai +20 more,,\r\n188,Expleo Solutions,3.9, 42 years old , 1k-5k Employees , Chennai +12 more,,\r\n189,Steel Strips Wheels,3.8, 33 years old , 1k-5k Employees , Chennai +35 more, Public ,Auto Components \r\n190,PayPal,3.9, 26 years old , 1k-5k Employees , Chennai +12 more, Forbes Global 2000 ,FinTech \r\n191,Sundaram Finance,4.2, 70 years old , 1k-5k Employees , Chennai +204 more, Public ,NBFC \r\n192,Ericsson,4.3, 148 years old , 10k-50k Employees , Chennai +151 more, Forbes Global 2000 ,Telecom \r\n193,JK Tyres,3.8, 73 years old , 1k-5k Employees , Chennai +130 more, Fortune India 500 ,Auto Components \r\n194,IDFC FIRST Bank,4.0, 6 years old , 10k-50k Employees , Chennai +588 more, Public ,Banking \r\n195,JLL,4.2, 25 years old , 10k-50k Employees , Chennai +70 more, Forbes Global 2000 ,Real Estate \r\n196,Quess,4.0, 17 years old , 1k-5k Employees , Chennai +542 more, Public ,BPO \r\n197,Elite Elevators,3.6, 16 years old , 51-200 Employees , Chennai +25 more,,\r\n198,Sanmina Sci,4.2, 44 years old , 1k-5k Employees , Chennai +10 more,,\r\n199,TVS Motor,4.1, 45 years old , 5k-10k Employees , Chennai +279 more, Public ,Automobile \r\n200,Hapag-Lloyd,3.9, 177 years old , 1k-5k Employees , Chennai +11 more,,\r\n201,Williams Lea,4.1, 204 years old , 1k-5k Employees , Chennai +14 more, Public ,BPO \r\n202,Hindustan Unilever,4.3, 152 years old , 10k-50k Employees , Chennai +436 more, Public ,FMCG \r\n203,Sopra Steria,4.0, 56 years old , 5k-10k Employees , Chennai +15 more, Conglomerate ,IT Services & Consulting \r\n204,Tiger Analytics,3.5, 13 years old , 1k-5k Employees , Chennai +8 more, Startup ,Analytics & KPO \r\n205,HDFC Life,4.1, 24 years old , 10k-50k Employees , Chennai +563 more, Public ,Insurance \r\n206,BigBasket,4.0, 13 years old , 10k-50k Employees , Chennai +116 more, Indian Unicorn ,Internet \r\n207,L&T Energy Hydrocarbon,3.9, 15 years old , 5k-10k Employees , Chennai +70 more,,\r\n208,Nibav Lifts,3.8, 5 years old , 1k-5k Employees , Chennai +29 more,,\r\n209,JBM Group,4.0, 41 years old , 1k-5k Employees , Chennai +85 more, Public ,Auto Components \r\n210,Faurecia,4.0, 27 years old , 1k-5k Employees , Chen

In [1465]:
with open("chennai.csv","w", encoding="cp1252", errors="ignore") as f:
    for i in g.split("\n"):
         f.write(i)

In [13]:
data1 = pd.read_csv("ahmedabad.csv",encoding = "cp1252")
data1

,Unnamed: 0,company_name,company_rating,old,total_employees,cities,type,industry
0,0,Zydus Lifesciences,4.2,72 years old,10k-50k Employees,Ahmedabad +152 more,Public,Pharma
1,1,Intas Pharmaceuticals,4.2,47 years old,10k-50k Employees,Ahmedabad +116 more,Fortune India 500,Pharma
2,2,Vodafone Idea,4.2,6 years old,5k-10k Employees,Ahmedabad +637 more,Public,Telecom
3,3,TTEC India,3.8,40 years old,1k-5k Employees,Ahmedabad +24 more,Public,BPO
4,4,Cadila Pharmaceuticals,3.6,73 years old,5k-10k Employees,Ahmedabad +114 more,Public,Pharma
...,...,...,...,...,...,...,...,...
9995,9995,Aadharshila School,4.9,NaN,11-50 Employees,Ahmedabad +1 more,NaN,NaN
9996,9996,Adroit Valuations,3.5,NaN,201-500 Employees,Ahmedabad +7 more,NaN,NaN
9997,9997,Meru Consultants,1.0,30 years old,NaN,Ahmedabad,NaN,NaN
9998,9998,Excare Laboratories,4.0,NaN,NaN,Ahmedabad,NaN,NaN
9999,9999,Mgli,4.5,NaN,NaN,Ahmedabad,NaN,NaN

In [15]:
data2 = pd.read_csv("bangalore.csv",encoding = "cp1252")
data2

,Unnamed: 0,company_name,company_rating,old,total_employees,cities,type,industry
0,0,TCS,3.8,56 years old,1 Lakh+ Employees,Mumbai +349 more,Public,IT Services & Consulting
1,1,Accenture,4.0,35 years old,1 Lakh+ Employees,Dublin +181 more,Public,IT Services & Consulting
2,2,Cognizant,3.9,30 years old,1 Lakh+ Employees,Teaneck. New Jersey. +169 more,Forbes Global 2000,IT Services & Consulting
3,3,Wipro,3.8,79 years old,1 Lakh+ Employees,Bangalore/Bengaluru +272 more,Public,IT Services & Consulting
4,4,Capgemini,3.8,57 years old,1 Lakh+ Employees,Paris +142 more,Public,IT Services & Consulting
...,...,...,...,...,...,...,...,...
8555,8555,Amazon,4.1,30 years old,1 Lakh+ Employees,Seattle +455 more,Public,Internet
8556,8556,IBM,4.1,113 years old,1 Lakh+ Employees,Armonk +149 more,Public,IT Services & Consulting
8557,8557,Reliance Retail,4.0,18 years old,1 Lakh+ Employees,Navi Mumbai +1013 more,NaN,NaN
8558,8558,HDB Financial Services,4.0,17 years old,1 Lakh+ Employees,Ahmedabad +959 more,NaN,NaN
8559,8559,Larsen & Toubro Limited,4.1,86 years old,10k-50k Employees,Mumbai +623 more,Public,Engineering & Construction

In [18]:
data3 = pd.read_csv("chennai.csv",encoding = "cp1252")
data3

,Unnamed: 0,company_name,company_rating,old,total_employees,cities,type,industry
0,0,TCS,3.8,56 years old,1 Lakh+ Employees,Chennai +349 more,Public,IT Services & Consulting
1,1,Cognizant,3.9,30 years old,1 Lakh+ Employees,Chennai +169 more,Forbes Global 2000,IT Services & Consulting
2,2,HCLTech,3.7,33 years old,1 Lakh+ Employees,Chennai +184 more,Public,IT Services & Consulting
3,3,Accenture,4.0,35 years old,1 Lakh+ Employees,Chennai +181 more,Public,IT Services & Consulting
4,4,Wipro,3.8,79 years old,1 Lakh+ Employees,Chennai +272 more,Public,IT Services & Consulting
...,...,...,...,...,...,...,...,...
9995,9995,Thulirsoftware Technologies,4.4,NaN,NaN,Chennai +1 more,NaN,NaN
9996,9996,B-FLUX MANAGEMENT SERVICES,2.7,13 years old,11-50 Employees (Global),Chennai +1 more,NaN,NaN
9997,9997,Nexus,4.1,24 years old,NaN,Chennai +12 more,NaN,NaN
9998,9998,Bharathi Matriculation Higher Secondary School,3.3,NaN,11-50 Employees,Chennai +5 more,NaN,NaN
9999,9999,Thiru Arooran Sugars,3.1,70 years old,501-1k Employees,Chennai +3 more,Public,NaN

In [21]:
data4 = pd.read_csv("gurugram.csv",encoding = "cp1252")
data4

,Unnamed: 0,company_name,company_rating,old,total_employees,cities,type,industry
0,0,TCS,3.8,56 years old,1 Lakh+ Employees,Mumbai +349 more,Public,IT Services & Consulting
1,1,Accenture,4.0,35 years old,1 Lakh+ Employees,Dublin +181 more,Public,IT Services & Consulting
2,2,Cognizant,3.9,30 years old,1 Lakh+ Employees,Teaneck. New Jersey. +169 more,Forbes Global 2000,IT Services & Consulting
3,3,Wipro,3.8,79 years old,1 Lakh+ Employees,Bangalore/Bengaluru +272 more,Public,IT Services & Consulting
4,4,Capgemini,3.8,57 years old,1 Lakh+ Employees,Paris +142 more,Public,IT Services & Consulting
...,...,...,...,...,...,...,...,...
8295,8295,Amazon,4.1,30 years old,1 Lakh+ Employees,Seattle +455 more,Public,Internet
8296,8296,IBM,4.1,113 years old,1 Lakh+ Employees,Armonk +149 more,Public,IT Services & Consulting
8297,8297,Reliance Retail,4.0,18 years old,1 Lakh+ Employees,Navi Mumbai +1013 more,NaN,NaN
8298,8298,HDB Financial Services,4.0,17 years old,1 Lakh+ Employees,Ahmedabad +959 more,NaN,NaN
8299,8299,Larsen & Toubro Limited,4.1,86 years old,10k-50k Employees,Mumbai +623 more,Public,Engineering & Construction

In [24]:
data5 = pd.read_csv("hyderabad.csv",encoding = "cp1252")
data5

,Unnamed: 0,company_name,company_rating,old,total_employees,cities,type,industry
0,0,TCS,3.8,56 years old,1 Lakh+ Employees,Hyderabad / Secunderabad +349 more,Public,IT Services & Consulting
1,1,Cognizant,3.9,30 years old,1 Lakh+ Employees,Hyderabad / Secunderabad +169 more,Forbes Global 2000,IT Services & Consulting
2,2,Wipro,3.8,79 years old,1 Lakh+ Employees,Hyderabad / Secunderabad +272 more,Public,IT Services & Consulting
3,3,Genpact,3.9,27 years old,1 Lakh+ Employees,Hyderabad / Secunderabad +112 more,Public,IT Services & Consulting
4,4,Accenture,4.0,35 years old,1 Lakh+ Employees,Hyderabad / Secunderabad +181 more,Public,IT Services & Consulting
...,...,...,...,...,...,...,...,...
9995,9995,The White Teak Company,3.7,8 years old,201-500 Employees,Hyderabad / Secunderabad +7 more,NaN,NaN
9996,9996,Bridgegap Consultants,3.9,10 years old,11-50 Employees,Hyderabad / Secunderabad +1 more,NaN,NaN
9997,9997,Advanced Medtech Solutions,3.6,11 years old,51-200 Employees,Hyderabad / Secunderabad +15 more,NaN,NaN
9998,9998,I.B.S.,3.7,NaN,NaN,Hyderabad / Secunderabad +13 more,NaN,NaN
9999,9999,India Ratings & Research,3.7,29 years old,51-200 Employees,Hyderabad / Secunderabad +12 more,NaN,NaN

In [27]:
data6 = pd.read_csv("indore.csv",encoding = "cp1252")
data6

,Unnamed: 0,company_name,company_rating,old,total_employees,cities,type,industry
0,0,Teleperformance,3.8,46 years old,50k-1 Lakh Employees,Indore +192 more,Forbes Global 2000,BPO
1,1,TCS,3.8,56 years old,1 Lakh+ Employees,Indore +349 more,Public,IT Services & Consulting
2,2,Cipla,4.1,89 years old,10k-50k Employees,Indore +239 more,Public,Pharma
3,3,TaskUs,3.5,16 years old,5k-10k Employees,Indore +24 more,NaN,NaN
4,4,ICICI Bank,4.0,30 years old,1 Lakh+ Employees,Indore +1295 more,Public,Banking
...,...,...,...,...,...,...,...,...
9995,9995,Kairos Hygiene,5.0,NaN,NaN,Indore,NaN,NaN
9996,9996,Jenburkt Pharmaceuticals,4.3,39 years old,501-1k Employees,Indore +11 more,Public,Pharma
9997,9997,Beri Udyog,4.0,46 years old,201-500 Employees,Indore +13 more,NaN,NaN
9998,9998,Honda Cars,4.4,29 years old,5k-10k Employees,Indore +91 more,Fortune India 500,Automobile
9999,9999,Ethos,3.5,21 years old,201-500 Employees,Indore +15 more,NaN,NaN

In [30]:
data7 = pd.read_csv("jaipur.csv",encoding = "cp1252")
data7

,Unnamed: 0,company_name,company_rating,old,total_employees,cities,type,industry
0,0,AU Small Finance Bank,4.4,28 years old,10k-50k Employees,Jaipur +409 more,Fortune India 500,Banking
1,1,Teleperformance,3.8,46 years old,50k-1 Lakh Employees,Jaipur +192 more,Forbes Global 2000,BPO
2,2,Genpact,3.9,27 years old,1 Lakh+ Employees,Jaipur +112 more,Public,IT Services & Consulting
3,3,ICICI Bank,4.0,30 years old,1 Lakh+ Employees,Jaipur +1295 more,Public,Banking
4,4,HDFC Bank,4.0,30 years old,1 Lakh+ Employees,Jaipur +1560 more,Public,Banking
...,...,...,...,...,...,...,...,...
8595,8595,Between The Brews,5.0,NaN,NaN,Jaipur,NaN,NaN
8596,8596,National Helpline for Senior Citizens,4.2,NaN,NaN,Agartala +5 more,NaN,NaN
8597,8597,Aash biotech,3.7,NaN,NaN,Jaipur +2 more,NaN,NaN
8598,8598,Jain Clave Polytech,4.0,NaN,NaN,Jaipur,NaN,NaN
8599,8599,Aagman Fitness Gym,4.5,NaN,NaN,Jaipur,NaN,NaN

In [33]:
data8 = pd.read_csv("mumbai.csv",encoding = "cp1252")
data8

,Unnamed: 0,company_name,company_rating,old,total_employees,cities,type,industry
0,0,TCS,3.8,56 years old,1 Lakh+ Employees,Mumbai +349 more,Public,IT Services & Consulting
1,1,Kotak Mahindra Bank,3.9,21 years old,50k-1 Lakh Employees,Mumbai +573 more,Public,Banking
2,2,Accenture,4.0,35 years old,1 Lakh+ Employees,Mumbai +181 more,Public,IT Services & Consulting
3,3,ICICI Bank,4.0,30 years old,1 Lakh+ Employees,Mumbai +1295 more,Public,Banking
4,4,Capgemini,3.8,57 years old,1 Lakh+ Employees,Mumbai +142 more,Public,IT Services & Consulting
...,...,...,...,...,...,...,...,...
9995,9995,Nvizion Solutions,4.5,NaN,51-200 Employees,Mumbai +1 more,NaN,NaN
9996,9996,Natvarlal Vepari & Co.,4.4,NaN,NaN,Mumbai +1 more,NaN,NaN
9997,9997,JetSynthesys,2.7,12 years old,201-500 Employees,Mumbai +2 more,Startup,IT Services & Consulting
9998,9998,Zee News,3.8,25 years old,10k-50k Employees,Mumbai +11 more,Public,Broadcasting
9999,9999,V Group Inc.,4.0,25 years old,51-200 Employees,Mumbai +5 more,NaN,NaN

In [36]:
data9 = pd.read_csv("noida.csv",encoding = "cp1252")
data9

,Unnamed: 0,company_name,company_rating,old,total_employees,cities,type,industry
0,0,iEnergizer,4.7,24 years old,10k-50k Employees,Noida +31 more,NaN,NaN
1,1,HCLTech,3.7,33 years old,1 Lakh+ Employees,Noida +184 more,Public,IT Services & Consulting
2,2,Genpact,3.9,27 years old,1 Lakh+ Employees,New York +112 more,Public,IT Services & Consulting
3,3,Tech Mahindra,3.7,38 years old,1 Lakh+ Employees,Pune +269 more,Public,IT Services & Consulting
4,4,TCS,3.8,56 years old,1 Lakh+ Employees,Mumbai +349 more,Public,IT Services & Consulting
...,...,...,...,...,...,...,...,...
9115,9115,STITCHED TEXTILES,3.5,NaN,NaN,Noida +2 more,NaN,NaN
9116,9116,Zindagi Technologies,3.8,NaN,51-200 Employees,Noida +2 more,NaN,NaN
9117,9117,Ritvi Innovations,1.6,NaN,NaN,Noida,NaN,NaN
9118,9118,Clickvaults,4.3,NaN,NaN,Noida,NaN,NaN
9119,9119,NG Digital Technology,5.0,NaN,NaN,Noida,NaN,NaN

In [39]:
data10 = pd.read_csv("pune.csv",encoding = "cp1252")
data10

,Unnamed: 0,company_name,company_rating,old,total_employees,cities,type,industry
0,0,TCS,3.8,56 years old,1 Lakh+ Employees,Pune +349 more,Public,IT Services & Consulting
1,1,Infosys,3.8,43 years old,1 Lakh+ Employees,Pune +182 more,Public,IT Services & Consulting
2,2,Cognizant,3.9,30 years old,1 Lakh+ Employees,Pune +169 more,Forbes Global 2000,IT Services & Consulting
3,3,Wipro,3.8,79 years old,1 Lakh+ Employees,Pune +272 more,Public,IT Services & Consulting
4,4,Capgemini,3.8,57 years old,1 Lakh+ Employees,Pune +142 more,Public,IT Services & Consulting
...,...,...,...,...,...,...,...,...
9995,9995,Preethi Kitchen Appliances,4.2,46 years old,1k-5k Employees,Pune +35 more,NaN,NaN
9996,9996,ACCURUB Technologies,4.0,13 years old,51-200 Employees,Pune +1 more,NaN,NaN
9997,9997,HLL Lifecare,3.7,58 years old,1k-5k Employees,Pune +93 more,NaN,NaN
9998,9998,Singularity AIX,3.7,NaN,NaN,Pune +2 more,NaN,NaN
9999,9999,Kgc Logistics,3.5,NaN,NaN,Pune +3 more,NaN,NaN

In [42]:
final_data = pd.concat([data1,data2,data3,data4,data5,data6,data7,data8,data9,data10]).reset_index()
final_data

,index,Unnamed: 0,company_name,company_rating,old,total_employees,cities,type,industry
0,0,0,Zydus Lifesciences,4.2,72 years old,10k-50k Employees,Ahmedabad +152 more,Public,Pharma
1,1,1,Intas Pharmaceuticals,4.2,47 years old,10k-50k Employees,Ahmedabad +116 more,Fortune India 500,Pharma
2,2,2,Vodafone Idea,4.2,6 years old,5k-10k Employees,Ahmedabad +637 more,Public,Telecom
3,3,3,TTEC India,3.8,40 years old,1k-5k Employees,Ahmedabad +24 more,Public,BPO
4,4,4,Cadila Pharmaceuticals,3.6,73 years old,5k-10k Employees,Ahmedabad +114 more,Public,Pharma
...,...,...,...,...,...,...,...,...,...
94575,9995,9995,Preethi Kitchen Appliances,4.2,46 years old,1k-5k Employees,Pune +35 more,NaN,NaN
94576,9996,9996,ACCURUB Technologies,4.0,13 years old,51-200 Employees,Pune +1 more,NaN,NaN
94577,9997,9997,HLL Lifecare,3.7,58 years old,1k-5k Employees,Pune +93 more,NaN,NaN
94578,9998,9998,Singularity AIX,3.7,NaN,NaN,Pune +2 more,NaN,NaN
94579,9999,9999,Kgc Logistics,3.5,NaN,NaN,Pune +3 more,NaN,NaN

In [45]:
final_data = final_data.drop(labels = ["index",	"Unnamed: 0"],axis = 1)
final_data

,company_name,company_rating,old,total_employees,cities,type,industry
0,Zydus Lifesciences,4.2,72 years old,10k-50k Employees,Ahmedabad +152 more,Public,Pharma
1,Intas Pharmaceuticals,4.2,47 years old,10k-50k Employees,Ahmedabad +116 more,Fortune India 500,Pharma
2,Vodafone Idea,4.2,6 years old,5k-10k Employees,Ahmedabad +637 more,Public,Telecom
3,TTEC India,3.8,40 years old,1k-5k Employees,Ahmedabad +24 more,Public,BPO
4,Cadila Pharmaceuticals,3.6,73 years old,5k-10k Employees,Ahmedabad +114 more,Public,Pharma
...,...,...,...,...,...,...,...
94575,Preethi Kitchen Appliances,4.2,46 years old,1k-5k Employees,Pune +35 more,NaN,NaN
94576,ACCURUB Technologies,4.0,13 years old,51-200 Employees,Pune +1 more,NaN,NaN
94577,HLL Lifecare,3.7,58 years old,1k-5k Employees,Pune +93 more,NaN,NaN
94578,Singularity AIX,3.7,NaN,NaN,Pune +2 more,NaN,NaN
94579,Kgc Logistics,3.5,NaN,NaN,Pune +3 more,NaN,NaN

In [48]:
g = final_data.to_csv()
g

',company_name,company_rating,old,total_employees,cities,type,industry\r\n0,Zydus Lifesciences,4.2, 72 years old , 10k-50k Employees , Ahmedabad +152 more, Public ,Pharma \r\n1,Intas Pharmaceuticals,4.2, 47 years old , 10k-50k Employees , Ahmedabad +116 more, Fortune India 500 ,Pharma \r\n2,Vodafone Idea,4.2, 6 years old , 5k-10k Employees , Ahmedabad +637 more, Public ,Telecom \r\n3,TTEC India,3.8, 40 years old , 1k-5k Employees , Ahmedabad +24 more, Public ,BPO \r\n4,Cadila Pharmaceuticals,3.6, 73 years old , 5k-10k Employees , Ahmedabad +114 more, Public ,Pharma \r\n5,Amneal Pharmaceuticals,4.3, 22 years old , 5k-10k Employees , Ahmedabad +26 more,,\r\n6,Torrent Pharmaceuticals,4.0, 53 years old , 10k-50k Employees , Ahmedabad +97 more, Public ,Pharma \r\n7,TCS,3.8, 56 years old , 1 Lakh+ Employees , Ahmedabad +349 more, Public ,IT Services & Consulting \r\n8,S&P Global,4.2, 164 years old , 10k-50k Employees , Ahmedabad +24 more, Public ,Analytics & KPO \r\n9,Lambda Therapeutic Research,4.7, 25 years old , 1k-5k Employees , Ahmedabad +6 more,,\r\n10,Arvind Group,4.1, 93 years old , 10k-50k Employees , Ahmedabad +80 more, Public ,Fashion & Textile \r\n11,HDFC Bank,4.0, 30 years old , 1 Lakh+ Employees , Ahmedabad +1560 more, Public ,Banking \r\n12,ICICI Bank,4.0, 30 years old , 1 Lakh+ Employees , Ahmedabad +1295 more, Public ,Banking \r\n13,Torrent Power,3.8, 28 years old , 5k-10k Employees , Ahmedabad +38 more, Public ,Power \r\n14,Tech Mahindra,3.7, 38 years old , 1 Lakh+ Employees , Ahmedabad +269 more, Public ,IT Services & Consulting \r\n15,Petpooja,4.4, 13 years old , 1k-5k Employees , Ahmedabad +53 more,,\r\n16,Kotak Mahindra Bank,3.9, 21 years old , 50k-1 Lakh Employees , Ahmedabad +573 more, Public ,Banking \r\n17,Adani Group,4.0, 36 years old , 10k-50k Employees , Ahmedabad +126 more, Public ,Power \r\n18,JBM Group,4.0, 41 years old , 1k-5k Employees , Ahmedabad +85 more, Public ,Auto Components \r\n19,Troikaa Pharmaceuticals,3.8, 41 years old , 1k-5k Employees , Ahmedabad +66 more,,\r\n20,Larsen & Toubro Limited,4.1, 86 years old , 10k-50k Employees , Ahmedabad +623 more, Public ,Engineering & Construction \r\n21,Axis Bank,3.9, 31 years old , 50k-1 Lakh Employees , Ahmedabad +1317 more, Public ,Banking \r\n22,K D Hospital,4.8, 6 years old , 201-500 Employees , Ahmedabad +3 more,,\r\n23,Shalby Hospitals,4.6, 30 years old , 1k-5k Employees , Ahmedabad +23 more, Public ,Healthcare \r\n24,suzuki motor gujarat,4.3,,, Ahmedabad +95 more,Fortune India 500 ,\r\n25,HDB Financial Services,4.0, 17 years old , 1 Lakh+ Employees , Ahmedabad +959 more,,\r\n26,Reliance Retail,4.0, 18 years old , 1 Lakh+ Employees , Ahmedabad +1013 more,,\r\n27,Otsuka Pharmaceutical India Private Limited,4.2, 8 years old , 501-1k Employees , Ahmedabad +31 more, Forbes Global 2000 ,Pharma \r\n28,Psp Projects,3.9, 16 years old , 1k-5k Employees , Ahmedabad +39 more,,\r\n29,Adani Enterprises,3.8, 36 years old ,10k-50k Employees , Ahmedabad +55 more, Public ,\r\n30,Tata Motors,4.2, 79 years old , 10k-50k Employees , Ahmedabad +433 more, Public ,Automobile \r\n31,Brainvire,4.0, 24 years old , 201-500 Employees , Ahmedabad +8 more,,\r\n32,Einfochips,3.5, 30 years old , 1k-5k Employees , Ahmedabad +10 more,,\r\n33,Electrotherm,4.2, 41 years old , 1k-5k Employees , Ahmedabad +33 more, Public ,Iron & Steel \r\n34,Advantmed,3.6, 19 years old , 501-1k Employees , Ahmedabad +6 more,,\r\n35,Jio,4.0, 6 years old , 50k-1 Lakh Employees , Ahmedabad +1175 more, Public ,Telecom \r\n36,Ford Motor,4.5, 121 years old , 5k-10k Employees , Ahmedabad +110 more, Public ,Automobile \r\n37,eClinicalWorks,3.9, 25 years old , 1k-5k Employees , Ahmedabad +12 more,,\r\n38,Eris Lifesciences,3.8, 17 years old , 1k-5k Employees , Ahmedabad +75 more, Public ,Pharma \r\n39,Adani Wilmar,4.2, 25 years old , 1k-5k Employees , Ahmedabad +154 more, Public ,FMCG \r\n40,Dishman Carbogen Amcis,3.8, 17 years old , 1k-5k Employees , Ahmedabad +10 more,,\r\n41,Honda Motorcycle & Scooter,4.1, 23 years old , 10k-50k Employees , Indore +217 more,,\r\n42,Bharti Airtel,4.1, 29 years old , 10k-50k Employees , Indore +660 more, Public ,Telecom \r\n43,Baxter International,4.1, 93 years old , 1k-5k Employees , Ahmedabad +26 more, Forbes Global 2000 ,Healthcare \r\n44,Medusind Solutions,3.9, 22 years old , 1k-5k Employees , Ahmedabad +8 more,,\r\n45,Reliance Industries,4.1, 47 years old , 1 Lakh+ Employees , Indore +687 more, Public ,Oil & Gas \r\n46,Veeda Clinical Research,4.1, 20 years old , 501-1k Employees , Ahmedabad +5 more,,\r\n47,Entigrity Solutions,4.2, 9 years old , 1k-5k Employees , Indore +12 more,,\r\n48,Harsha Engineers,4.2, 38 years old , 1k-5k Employees , Ahmedabad +8 more,,\r\n49,IMS People,3.5, 18 years old , 1k-5k Employees , Indore +22 more,,\r\n50,Adani Green Energy,4.2, 9 years old , 1k-5k Employees , Indore +67 more, Fortune India 500 ,Power \r\n51,Adani Power,3.9, 18 years old , 1k-5k Employees , Mundra +84 more, Public ,Power \r\n52,Astral Pipe,4.3,, 1-10 Employees , Indore +96 more, Fortune India 500 ,Building Material \r\n53,Cygnet Infotech,3.7, 24 years old , 1k-5k Employees , Ahmedabad +9 more,,\r\n54,Mastek,3.7, 42 years old , 1k-5k Employees , Ahmedabad +18 more, Public ,IT Services & Consulting \r\n55,BYJU\'S,3.1, 13 years old , 10k-50k Employees , Indore +307 more, Indian Unicorn ,EdTech \r\n56,IndusInd Bank,3.7, 30 years old , 10k-50k Employees , Indore +689 more, Public ,Banking \r\n57,IDFC FIRST Bank,4.0, 6 years old , 10k-50k Employees , Indore +588 more, Public ,Banking \r\n58,Hitech Digital Solutions,4.1, 32 years old , 1k-5k Employees , Ahmedabad +15 more,,\r\n59,Ascendum KPS,4.2, 23 years old ,1k-5k Employees , Indore +11 more,,\r\n60,Paperchase Accountancy,3.2, 35 years old ,1k-5k Employees , Ahmedabad +3 more,,\r\n61,Nirma,4.3, 34 years old , 10k-50k Employees , Ahmedabad +51 more, Fortune India 500 ,FMCG \r\n62,LendingKart,3.2, 10 years old , 1k-5k Employees , Ahmedabad +27 more, Public ,NBFC \r\n63,Aculife Healthcare,3.7, 10 years old , 1k-5k Employees , Ahmedabad +26 more,,\r\n64,Yazaki,3.9, 83 years old , 10k-50k Employees , Ahmedabad +68 more,,\r\n65,MAS Financial Services,3.7, 29 years old , 1k-5k Employees , Ahmedabad +99 more, Public ,Financial Services \r\n66,QX Global Group,3.4, 21 years old , 1k-5k Employees , Ahmedabad +15 more, Public ,IT Services & Consulting \r\n67,Uplers,4.2, 12 years old , 501-1k Employees , Ahmedabad +12 more,,\r\n68,Sapphire Software Solutions (India),4.5, 24 years old , 51-200 Employees , Ahmedabad +3 more,,\r\n69,Vadilal Industries,4.1, 117 years old , 501-1k Employees , Ahmedabad +76 more, Public ,FMCG \r\n70,NextComm Corporation,4.9, 7 years old ,1k-5k Employees , Ahmedabad +11 more,,\r\n71,Havmor Ice Cream,4.4, 80 years old , 1k-5k Employees , Ahmedabad +53 more,,\r\n72,Sterlite Technologies,3.8, 36 years old , 1k-5k Employees , Ahmedabad +80 more, Public ,Hardware & Networking \r\n73,Cliantha Research,4.0, 20 years old , 501-1k Employees , Ahmedabad +8 more, Public ,Clinical Research \r\n74,M Square Media,4.6,,, Ahmedabad +42 more,,\r\n75,Hidden Brains InfoTech,3.7, 21 years old , 201-500 Employees , Ahmedabad +4 more,,\r\n76,Zydus Hospital,4.3, 9 years old , 1k-5k Employees , Ahmedabad +9 more, Public ,Healthcare \r\n77,Tatvasoft,3.8, 23 years old , 1k-5k Employees , Ahmedabad +2 more,,\r\n78,Egniol Services,3.9,6 years old ,, Ahmedabad +5 more,,\r\n79,Yes Bank,3.9, 20 years old , 10k-50k Employees , Ahmedabad +447 more, Public ,Banking \r\n80,Gtpl Hathway,4.1, 18 years old , 501-1k Employees , Ahmedabad +39 more, Public ,Broadcasting \r\n81,Zydus Wellness,3.9, 36 years old , 501-1k Employees , Ahmedabad +98 more, Public ,FMCG \r\n82,Kataria Automobiles,3.9, 34 years old , 201-500 Employees , Ahmedabad +21 more,,\r\n83,Adani Ports and SEZ,3.9, 26 years old , 1k-5k Employees , Ahmedabad +69 more, Public ,Ports & Shipping \r\n84,Krishna Maruti,4.0, 30 years old , 1k-5k Employees , Ahmedabad +33 more,,\r\n85,Crest Data Systems,3.5, 11 years old , 501-1k Employees , Ahmedabad +2 more,,\r\n86,AU Small Finance Bank,4.4, 28 years old , 10k-50k Employees , Ahmedabad +409 more, Fortune India 500 ,Banking \r\n87,Corona Remedies,4.0, 20 years old , 1k-5k Employees , Ahmedabad +50 more,,\r\n88,Vestas,4.3, 27 years old , 1k-5k Employees , Ahmedabad +43 more, Forbes Global 2000 ,Power \r\n89,Jindal Worldwide,3.5, 38 years old , 1k-5k Employees , Ahmedabad +3 more, Public ,Fashion & Textile \r\n90,CARS24,3.7, 9 years old , 5k-10k Employees , Ahmedabad +148 more, Indian Unicorn ,Internet \r\n91,DMart,4.0, 22 years old , 10k-50k Employees , Ahmedabad +213 more, Fortune India 500 ,Retail \r\n92,Amnex Infotechnologies,3.5, 16 years old , 501-1k Employees , Ahmedabad +16 more,,\r\n93,Subros,4.0, 39 years old , 1k-5k Employees , Ahmedabad +60 more, Public ,Auto Components \r\n94,QX,3.6, 21 years old , 1k-5k Employees , Ahmedabad +4 more,,\r\n95,Claris Lifesciences Ahmedabad,3.1, 25 years old , 1k-5k Employees , Ahmedabad +15 more, Public ,Healthcare \r\n96,Lincoln Pharmaceuticals,3.8, 45 years old , 1k-5k Employees , Ahmedabad +21 more, Public ,Pharma \r\n97,Home Credit Finance,4.1, 12 years old , 10k-50k Employees , Ahmedabad +116 more,,\r\n98,Dineshchandra R Agarwal Infracon,4.2, 52 years old , 1k-5k Employees , Ahmedabad +54 more,,\r\n99,JustDial,3.6, 28 years old , 10k-50k Employees , Ahmedabad +181 more, Public ,Internet \r\n100,Hindustan Coca Cola Beverages,4.3, 27 years old , 5k-10k Employees , Ahmedabad +214 more,,\r\n101,Analytix Business Solutions,3.5, 18 years old , 501-1k Employees , Ahmedabad +5 more,,\r\n102,L&T Construction,4.1, 80 years old , 5k-10k Employees , Ahmedabad +360 more, Public ,Engineering & Construction \r\n103,OneClick IT Consultancy,4.7, 12 years old , 51-200 Employees , Ahmedabad +2 more,,\r\n104,GVK Emergency Management and Research Institute,3.7, 19 years old , 10k-50k Employees , Ahmedabad +149 more,,\r\n105,Viatris,4.2, 4 years old , 10k-50k Employees , Ahmedabad +69 more, Forbes Global 2000 ,Pharma \r\n106,Concord Biotech,3.7, 24 years old , 501-1k Employees , Ahmedabad +12 more, Public ,Pharma \r\n107,Sanghi Industries,3.7, 39 years old , 501-1k Employees , Ahmedabad +24 more, Public ,Building Material \r\n108,Piramal Pharma,4.0, 36 years old , 1k-5k Employees , Ahmedabad +51 more, Public ,Pharma \r\n109,Astral Adhesives,4.1, 37 years old , 501-1k Employees , Ahmedabad +108 more,,\r\n110,Maxgen Technologies,4.5, 11 years old , 201-500 Employees , Ahmedabad +7 more,,\r\n111,Health Care Global Enterprises,4.2, 35 years old , 5k-10k Employees , Ahmedabad +40 more, Public ,Healthcare \r\n112,Meditab Software,3.2, 19 years old , 1k-5k Employees , Ahmedabad +2 more,,\r\n113,Microlink Solutions,3.9, 28 years old , 201-500 Employees , Ahmedabad +22 more,,\r\n114,Montecarlo Construction,4.3, 29 years old , 1k-5k Employees , Ahmedabad +66 more,,\r\n115,Sadbhav Engineering,4.4, 36 years old , 1k-5k Employees , Ahmedabad +63 more, Public ,Engineering & Construction \r\n116,Startek,3.3, 7 years old , 10k-50k Employees , Ahmedabad +72 more, Public ,BPO \r\n117,e-Procurement Technologies,3.5, 18 years old , 501-1k Employees , Ahmedabad +17 more,,\r\n118,Jana Small Finance Bank,3.9, 18 years old , 10k-50k Employees , Ahmedabad +354 more, Public ,Banking \r\n119,Confiance BizSol Private Limited,3.6, 7 years old , 501-1k Employees , Ahmedabad +2 more,,\r\n120,Aia Engineering,4.2, 45 years old , 1k-5k Employees , Ahmedabad +3 more, Public ,Industrial Machinery \r\n121,La-Gajjar Machineries,4.1, 89 years old , 51-200 Employees , Ahmedabad +25 more,,\r\n122,Hyperlink Infosystem,4.6, 13 years old , 1k-5k Employees , Ahmedabad,,\r\n123,Emcure Pharmaceuticals,3.8, 43 years old , 5k-10k Employees , Ahmedabad +96 more, Fortune India 500 ,Pharma \r\n124,Apcer Life Sciences,3.7, 17 years old , 51-200 Employees , Ahmedabad +4 more,,\r\n125,Simform,3.5, 14 years old , 501-1k Employees , Ahmedabad,,\r\n126,CIMS Hospital,3.8, 14 years old , 201-500 Employees , Ahmedabad +16 more,,\r\n127,Teleysia Networks,3.7, 16 years old , 201-500 Employees , Ahmedabad +33 more,,\r\n128,Wagh Bakri Tea Group,4.2, 109 years old , 1k-5k Employees , Ahmedabad +27 more,,\r\n129,Kunal Structure,3.8, 18 years old , 201-500 Employees , Ahmedabad +25 more,,\r\n130,Monte Carlo,4.2, 40 years old , 201-500 Employees , Ahmedabad +77 more, Public ,Fashion & Textile \r\n131,Asian Granito India,3.8, 24 years old , 1k-5k Employees , Ahmedabad +53 more, Public ,Building Material \r\n132,Kogta Financial India Limited,4.8, 28 years old , 1k-5k Employees , Ahmedabad +206 more, Public ,NBFC \r\n133,ICICI Prudential Life Insurance,4.1, 24 years old , 10k-50k Employees , Ahmedabad +450 more, Public ,Insurance \r\n134,Bosch Rexroth India,4.0, 23 years old , 501-1k Employees , Ahmedabad +18 more,,\r\n135,Chiripal Industries,3.6, 52 years old , 1k-5k Employees , Ahmedabad +4 more, Public ,Fashion & Textile \r\n136,IIFL Finance,4.0, 29 years old , 10k-50k Employees , Ahmedabad +673 more, Public ,NBFC \r\n137,Apollo Hospitals,4.2, 41 years old , 10k-50k Employees , Ahmedabad +189 more, Public ,Healthcare \r\n138,Piramal Group,4.0, 44 years old , 10k-50k Employees , Ahmedabad +122 more, Fortune India 500 ,Financial Services \r\n139,Vrinsoft Technology,4.7, 15 years old , 11-50 Employees (Global) , Ahmedabad +1 more,,\r\n140,Unison Pharmaceuticals,4.2, 43 years old , 501-1k Employees , Ahmedabad +4 more,,\r\n141,Sodexo,4.1, 16 years old , 10k-50k Employees , Ahmedabad +131 more, Forbes Global 2000 ,Facility Management Services \r\n142,Abellon Clean Energy,3.7, 16 years old , 501-1k Employees , Ahmedabad +17 more, Public ,Other \r\n143,Gateway Group,2.8, 27 years old , 501-1k Employees , Ahmedabad +6 more,,\r\n144,Bajaj Finance,4.1, 37 years old , 10k-50k Employees , Ahmedabad +771 more,,\r\n145,Fedora Solutions,3.5, 20 years old , 501-1k Employees , Ahmedabad +1 more,,\r\n146,Media NV,4.8,,,Ahmedabad,,\r\n147,Croma,4.0, 18 years old , 5k-10k Employees , Ahmedabad +147 more,,\r\n148,Jay Chemical Industries,4.2, 57 years old , 1k-5k Employees , Ahmedabad +21 more,,\r\n149,Adani Solar,4.0, 9 years old , 1k-5k Employees , Ahmedabad +28 more, Public ,Power \r\n150,Indiamart Intermesh,3.6, 28 years old , 5k-10k Employees , Ahmedabad +145 more,,\r\n151,Ingersoll Rand,4.3, 52 years old , 501-1k Employees , Ahmedabad +28 more, Public ,Industrial Machinery \r\n152,Sintex Industries,4.1, 93 years old , 5k-10k Employees , Ahmedabad +51 more, Public ,Industrial Machinery \r\n153,BrainerHub,4.6, 3 years old , 51-200 Employees , Ahmedabad +2 more,,\r\n154,Panamax Infotech,3.2, 23 years old , 201-500 Employees , Ahmedabad +3 more,,\r\n155,Maxxis Rubber,3.6, 9 years old , 51-200 Employees , Ahmedabad +16 more,,\r\n156,Adani Gas,3.5, 20 years old , 501-1k Employees , Ahmedabad +39 more, Public ,Oil & Gas \r\n157,HDFC Life,4.1, 24 years old , 10k-50k Employees , Ahmedabad +563 more, Public ,Insurance \r\n158,Gtpl Broadband,3.9, 18 years old , 1k-5k Employees (Global) , Ahmedabad +41 more,,\r\n159,Silver Touch Technologies,3.6, 32 years old , 1k-5k Employees , Ahmedabad +26 more, Public ,IT Services & Consulting \r\n160,Gtpl Broadband,3.9, 18 years old , 1k-5k Employees (Global) , Ahmedabad +41 more,,\r\n161,Udaan,4.0, 8 years old ,1k-5k Employees , Ahmedabad +333 more, Indian Unicorn ,\r\n162,Indus Towers,4.0, 17 years old , 1k-5k Employees , Ahmedabad +159 more, Fortune India 500 ,Telecom \r\n163,Amazon,4.1, 30 years old , 1 Lakh+ Employees , Ahmedabad +455 more, Public ,Internet \r\n164,Flourish Pure Foods,1.8, 14 years old , 51-200 Employees , Ahmedabad +9 more,,\r\n165,Sapphire Infocom,4.9, 30 years old , 11-50 Employees , Ahmedabad +2 more,,\r\n166,Asian Paints,4.1, 82 years old , 5k-10k Employees , Ahmedabad +443 more, Public ,Chemicals \r\n167,Sophos Technologies,3.8, 39 years old , 1k-5k Employees , Ahmedabad +6 more,,\r\n168,Dev Information Technology,3.9, 27 years old , 501-1k Employees , Ahmedabad +28 more, Public ,IT Services & Consulting \r\n169,Samsung,4.1, 55 years old , 50k-1 Lakh Employees , Ahmedabad +499 more, Public ,Consumer Electronics & Appliances \r\n170,Motherson Automotive Technologies and Engineering,4.0, 27 years old , 501-1k Employees , Ahmedabad +53 more,,\r\n171,ICICI Lombard General Insurance Company,3.8, 23 years old , 10k-50k Employees , Ahmedabad +264 more, Public ,Insurance \r\n172,E2logy Software Solutions,4.4, 19 years old , 51-200 Employees , Ahmedabad +2 more,,\r\n173,Doshion,2.3, 46 years old , 1-10 Employees , Ahmedabad +6 more,,\r\n174,SGS,4.0, 146 years old ,1k-5k Employees , Ahmedabad +111 more, Forbes Global 2000 ,\r\n175,La Renon Healthcare,3.5, 17 years old , 501-1k Employees , Ahmedabad +29 more,,\r\n176,Apexon,3.4, 28 years old , 1k-5k Employees , Ahmedabad +15 more,,\r\n177,Volansys Technologies,3.5, 16 years old , 201-500 Employees , Ahmedabad +1 more,,\r\n178,Paytm,3.5, 14 years old , 10k-50k Employees , Ahmedabad +327 more, Public ,FinTech \r\n179,Symphony,4.1, 36 years old , 201-500 Employees , Ahmedabad +57 more, Public ,Consumer Electronics & Appliances \r\n180,West Coast Pharmaceuticals,3.5, 59 years old , 51-200 Employees , Ahmedabad +8 more,,\r\n181,Delhivery,4.0, 13 years old , 10k-50k Employees , Ahmedabad +632 more, Fortune India 500 ,Logistics \r\n182,Group Bayport,4.4, 12 years old , 1k-5k Employees , Ahmedabad +3 more,,\r\n183,Mehta Cad Cam Systems,3.8, 35 years old , 51-200 Employees , Ahmedabad +15 more,,\r\n184,Matter Motor Works,3.8, 5 years old , 501-1k Employees , Ahmedabad +1 more,,\r\n185,Ferromatik Milacron,3.7, 140 years old , 11-50 Employees , Ahmedabad +7 more,,\r\n186,Sterling Hospitals,4.0, 23 years old , 1k-5k Employees , Ahmedabad +12 more, Public ,Healthcare \r\n187,BigBasket,4.0, 13 years old , 10k-50k Employees , Ahmedabad +116 more, Indian Unicorn ,Internet \r\n188,FCC Clutch,4.2, 85 years old , 501-1k Employees , Ahmedabad +22 more,,\r\n189,Fincare Small Finance Bank,4.1, 17 years old , 10k-50k Employees , Ahmedabad +363 more,,\r\n190,Flipkart,4.0, 17 years old , 10k-50k Employees , Ahmedabad +516 more, Public ,Internet \r\n191,Deep Industries,3.5, 33 years old , 1k-5k Employees , Ahmedabad +9 more, Public ,Oil & Gas \r\n192,PressureJet Systems,4.4, 28 years old , 51-200 Employees , Ahmedabad +6 more,,\r\n193,Bajaj Finserv,4.1, 17 years old , 50k-1 Lakh Employees , Ahmedabad +904 more, Public ,Financial Services \r\n194,Jekson Vision,4.0, 23 years old , 201-500 Employees , Ahmedabad +5 more,,\r\n195,SOPAN,4.0, 23 years old , 1k-5k Employees , Ahmedabad +25 more,,\r\n196,Radixweb,3.0, 24 years old , 501-1k Employees , Ahmedabad +2 more,,\r\n197,upGrad,3.8, 9 years old , 5k-10k Employees , Ahmedabad +38 more, Indian Unicorn ,EdTech \r\n198,Baxter Pharmaceuticals,4.3,,,Ahmedabad +5 more,,\r\n199,Max Life Insurance,4.2, 24 years old , 10k-50k Employees , Ahmedabad +402 more,,\r\n200,Wipro,3.8, 79 years old , 1 Lakh+ Employees , Ahmedabad +272 more, Public ,IT Services & Consulting \r\n201,Rysun Labs,3.4, 23 years old , 201-500 Employees , Ahmedabad +5 more,,\r\n202,UltraTech Cement,4.2, 41 years old , 10k-50k Employees , Ahmedabad +433 more, Public ,Building Material \r\n203,Highly Electrical Appliances India,3.3, 11 years old , 51-200 Employees , Ahmedabad +3 more,,\r\n204,GSP Crop Science,4.0, 39 years old , 501-1k Employees , Ahmedabad +36 more,,\r\n205,Priya Softweb Solutions,4.0, 24 years old , 201-500 Employees , Ahmedabad +3 more,,\r\n206,Line O Matic Graphic Industries,3.3, 27 years old , 201-500 Employees , Ahmedabad +2 more,,\r\n207,Komal Tex Fab,3.4, 43 years old , 51-200 Employees , Ahmedabad +2 more,,\r\n208,Quess,4.0, 17 years old , 1k-5k Employees , Ahmedabad +542 more, Public ,BPO \r\n209,SPEC INDIA,4.6, 37 years old , 201-500 Employees , Ahmedabad +3 more,,\r\n210,IndiaNIC Infotech,3.6, 27 years old , 501-1k Employees , Ahmedabad +2 more,,\r\n211,Welspun Transformation Services Limited,4.1,, 5k-10k Employees , Ahmedabad +7 more,,\r\n212,SATTRIX Information Security,3.3, 11 years old 

In [55]:
os.getcwd()

'F:\\Study (E)\\Data Science\\Grras\\Projects\\Job Seeker (Ambition box)\\Ambition Box Data (Cleaned Data)'

In [65]:
os.chdir("F:\\Study (E)\\Data Science\\Grras\\Projects\\Job Seeker (Ambition box)\\")

In [68]:
with open("final_data.csv","w") as f:
    for i in g.split("\n"):
        f.write(i)